// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_examples.hpp"
#include "./common_xmlization.hpp"

#include <dummy/iteration.hpp>
#include <dummy/stringification.hpp>

#include <filesystem>

namespace our = dummy;

namespace test {
namespace common {
namespace examples {

template<typename T>
struct StaticTypeName;

template<>
struct StaticTypeName<
  our::types::ILangString
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::ILangString
>::name = "ILangString";

template<>
struct StaticTypeName<
  our::types::ILangStringSet
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::ILangStringSet
>::name = "ILangStringSet";

template<>
struct StaticTypeName<
  our::types::IIecContent
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::IIecContent
>::name = "IIecContent";

template<>
struct StaticTypeName<
  our::types::IOtherContent
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::IOtherContent
>::name = "IOtherContent";

template<>
struct StaticTypeName<
  our::types::ISpecification
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::ISpecification
>::name = "ISpecification";

template<>
struct StaticTypeName<
  our::types::ISomething
> {
  static const char* name;
};
const char* StaticTypeName<
  our::types::ISomething
>::name = "ISomething";

std::shared_ptr<
  our::types::ILangString
> LoadLangString(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::ILangString
  > instance(
    std::dynamic_pointer_cast<
      our::types::ILangString
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to ILangString from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::ILangString
> LoadMinLangString() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "langString"
      / "minimal.xml"
  );

  return LoadLangString(
    path
  );
}

std::shared_ptr<
  our::types::ILangString
> LoadMaxLangString() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "langString"
      / "maximal.xml"
  );

  return LoadLangString(
    path
  );
}

std::shared_ptr<
  our::types::ILangStringSet
> LoadLangStringSet(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::ILangStringSet
  > instance(
    std::dynamic_pointer_cast<
      our::types::ILangStringSet
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to ILangStringSet from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::ILangStringSet
> LoadMinLangStringSet() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "langStringSet"
      / "minimal.xml"
  );

  return LoadLangStringSet(
    path
  );
}

std::shared_ptr<
  our::types::ILangStringSet
> LoadMaxLangStringSet() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "langStringSet"
      / "maximal.xml"
  );

  return LoadLangStringSet(
    path
  );
}

std::shared_ptr<
  our::types::IIecContent
> LoadIecContent(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::IIecContent
  > instance(
    std::dynamic_pointer_cast<
      our::types::IIecContent
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to IIecContent from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::IIecContent
> LoadMinIecContent() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "iecContent"
      / "minimal.xml"
  );

  return LoadIecContent(
    path
  );
}

std::shared_ptr<
  our::types::IIecContent
> LoadMaxIecContent() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "iecContent"
      / "maximal.xml"
  );

  return LoadIecContent(
    path
  );
}

std::shared_ptr<
  our::types::IOtherContent
> LoadOtherContent(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::IOtherContent
  > instance(
    std::dynamic_pointer_cast<
      our::types::IOtherContent
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to IOtherContent from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::IOtherContent
> LoadMinOtherContent() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "otherContent"
      / "minimal.xml"
  );

  return LoadOtherContent(
    path
  );
}

std::shared_ptr<
  our::types::IOtherContent
> LoadMaxOtherContent() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "otherContent"
      / "maximal.xml"
  );

  return LoadOtherContent(
    path
  );
}

std::shared_ptr<
  our::types::ISpecification
> LoadSpecification(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::ISpecification
  > instance(
    std::dynamic_pointer_cast<
      our::types::ISpecification
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to ISpecification from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::ISpecification
> LoadMinSpecification() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "specification"
      / "minimal.xml"
  );

  return LoadSpecification(
    path
  );
}

std::shared_ptr<
  our::types::ISpecification
> LoadMaxSpecification() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "specification"
      / "maximal.xml"
  );

  return LoadSpecification(
    path
  );
}

std::shared_ptr<
  our::types::ISomething
> LoadSomething(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    our::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    our::types::ISomething
  > instance(
    std::dynamic_pointer_cast<
      our::types::ISomething
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      our::common::Concat(
        "Failed to cast the instance to ISomething from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  our::types::ISomething
> LoadMinSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "minimal.xml"
  );

  return LoadSomething(
    path
  );
}

std::shared_ptr<
  our::types::ISomething
> LoadMaxSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "maximal.xml"
  );

  return LoadSomething(
    path
  );
}

}  // namespace examples
}  // namespace common
}  // namespace test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
