/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed

using Path = System.IO.Path;

namespace dummy.Tests
{
    /// <summary>
    /// Provide methods to load instances from JSON test data.
    /// </summary>
    public static class CommonJsonization
    {
        public static Aas.Item LoadMaximalItem()
        {
            string path = Path.Combine(
                Aas.Tests.Common.TestDataDir,
                "Json",
                "Expected",
                "Item",
                "maximal.json");

            var node = Aas.Tests.CommonJson.ReadFromFile(path);

            var instance = Aas.Jsonization.Deserialize.ItemFrom(
                node);

            return instance;
        }  // public static Aas.Item LoadMaximalItem

        public static Aas.Item LoadMinimalItem()
        {
            string path = Path.Combine(
                Aas.Tests.Common.TestDataDir,
                "Json",
                "Expected",
                "Item",
                "minimal.json");

            var node = Aas.Tests.CommonJson.ReadFromFile(path);

            var instance = Aas.Jsonization.Deserialize.ItemFrom(
                node);

            return instance;
        }  // public static Aas.Item LoadMinimalItem

        public static Aas.Something LoadMaximalSomething()
        {
            string path = Path.Combine(
                Aas.Tests.Common.TestDataDir,
                "Json",
                "Expected",
                "Something",
                "maximal.json");

            var node = Aas.Tests.CommonJson.ReadFromFile(path);

            var instance = Aas.Jsonization.Deserialize.SomethingFrom(
                node);

            return instance;
        }  // public static Aas.Something LoadMaximalSomething

        public static Aas.Something LoadMinimalSomething()
        {
            string path = Path.Combine(
                Aas.Tests.Common.TestDataDir,
                "Json",
                "Expected",
                "Something",
                "minimal.json");

            var node = Aas.Tests.CommonJson.ReadFromFile(path);

            var instance = Aas.Jsonization.Deserialize.SomethingFrom(
                node);

            return instance;
        }  // public static Aas.Something LoadMinimalSomething
    }  // class CommonJsonization
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
