/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.copying;

import java.util.List;
import java.util.ArrayList;
import dummy.common.*;
import dummy.types.model.IClass;
import dummy.visitation.AbstractTransformer;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;

/**
 * Allow for making shallow and deep copies of AAS model instances.
 */
public class Copying
{
    private static final _ShallowCopier shallowCopierInstance = new _ShallowCopier();

    private static final _DeepCopier deepCopierInstance = new _DeepCopier();

    /**
     * Make a shallow copy of {@code that}.
     *
     * <p>All the properties are copied by reference. This includes also the lists.
     * Hence, a list property is copied by reference, and not, as sometimes might be
     * expected, as a new list of underlying references.
     *
     * @param that to be copied in a shallow manner
     */
    @SuppressWarnings("unchecked")
    public static <T extends IClass> T shallow(T that) {
        return (T) shallowCopierInstance.transform(that);
    }

    /**
     * Make a recursively a deep copy of {@code that}.
     *
     * @param that to be deeply copied in a recursive manner
     */
    @SuppressWarnings("unchecked")
    public static <T extends IClass> T deep(T that) {
        return (T) deepCopierInstance.transform(that);
    }

    /**
     * Dispatch the making of shallow copies.
     */
    private static class _ShallowCopier extends AbstractTransformer<IClass> {
        @Override
        public IClass transformSomething(
            ISomething that
        ) {
            return new Something(
                that.getSomeBool(),
                that.getSomeInt(),
                that.getSomeFloat(),
                that.getSomeString(),
                that.getSomeBytes());
        }
    }

    /** Dispatch the making of deep copies. */
    private static class _DeepCopier extends AbstractTransformer<IClass> {
        @Override
        public IClass transformSomething (
            ISomething that
        ) {
            return new Something(
                that.getSomeBool(),
                that.getSomeInt(),
                that.getSomeFloat(),
                that.getSomeString(),
                that.getSomeBytes()
            );
        }
    }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
