package types_descend_test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"path/filepath"
	"testing"
	aastesting "github.com/dummy-works/dummy/aastesting"
)

func TestDescendOnceOnAnInstanceOfFirst(
	t *testing.T,
) {
	instance := aastesting.MustLoadMaximalFirst()

	expectedPth := filepath.Join(
		aastesting.TestDataDir,
		"DescendOnce",
		"First",
		"maximal.json.trace",
	)

	onlyOnce := true

	message := compareOrRerecordTrace(
		instance,
		expectedPth,
		onlyOnce,
	)
	if message != nil {
		t.Fatal(*message)
	}
}

func TestDescendOnceOnAnInstanceOfSecond(
	t *testing.T,
) {
	instance := aastesting.MustLoadMaximalSecond()

	expectedPth := filepath.Join(
		aastesting.TestDataDir,
		"DescendOnce",
		"Second",
		"maximal.json.trace",
	)

	onlyOnce := true

	message := compareOrRerecordTrace(
		instance,
		expectedPth,
		onlyOnce,
	)
	if message != nil {
		t.Fatal(*message)
	}
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
