/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Our = dummy;  // renamed

// We need to use System.MemoryExtension.SequenceEqual.
using System;  // can't alias
using System.Collections.Generic;  // can't alias

using Nodes = System.Text.Json.Nodes;

using NUnit.Framework;  // can't alias

namespace dummy.Tests
{
    public class TestCopying
    {
        /// <summary>
        /// Check that the context is a deep copy of the visited instance.
        /// </summary>
        /// <remarks>
        /// The copy has to equal the original by value, while it must share none
        /// of the mutable objects with it.
        /// </remarks>
        internal class DeepCopyChecker
            : Our.Visitation.AbstractTransformerWithContext<Our.IClass, bool>
        {
            private static bool BytesEqualButDistinct(
                byte[] that,
                byte[] other)
            {
                // NOTE (mristin):
                // A byte[] implicitly converts to a ReadOnlySpan, which compares by content.
                // See: https://stackoverflow.com/a/48599119/1600678
                return (
                    !ReferenceEquals(that, other)
                    && ((System.ReadOnlySpan<byte>)that).SequenceEqual(other));
            }

            private static bool JsonNodesEqualButDistinct(
                Nodes.JsonNode that,
                Nodes.JsonNode other)
            {
                // NOTE (mristin):
                // A JsonNode compares only by reference, so we compare the canonical
                // JSON text.
                return (
                    !ReferenceEquals(that, other)
                    && that.ToJsonString() == other.ToJsonString());
            }

            public override bool TransformSomething(
                Our.ISomething that,
                Our.IClass other)
            {
                if (!(other is Our.Something casted) || ReferenceEquals(that, other))
                {
                    return false;
                }

                return (
                    Check_ListOf_jsonValue(
                        that.Values,
                        casted.Values)
                    && Check_TupleOf4_string_jsonValue_jsonArray_jsonObject(
                        that.TupleWithJson,
                        casted.TupleWithJson));
            }

            private bool Check_ListOf_jsonValue(
                List<Nodes.JsonNode> that,
                List<Nodes.JsonNode> other)
            {
                if (ReferenceEquals(that, other) || that.Count != other.Count)
                {
                    return false;
                }

                for (int i = 0; i < that.Count; i++)
                {
                    if (!(
                        JsonNodesEqualButDistinct(
                            that[i],
                            other[i])))
                    {
                        return false;
                    }
                }

                return true;
            }

            private bool Check_TupleOf4_string_jsonValue_jsonArray_jsonObject(
                (string, Nodes.JsonNode, Nodes.JsonArray, Nodes.JsonObject) that,
                (string, Nodes.JsonNode, Nodes.JsonArray, Nodes.JsonObject) other)
            {
                return (
                    that.Item1 == other.Item1
                    && JsonNodesEqualButDistinct(
                        that.Item2,
                        other.Item2)
                    && JsonNodesEqualButDistinct(
                        that.Item3,
                        other.Item3)
                    && JsonNodesEqualButDistinct(
                        that.Item4,
                        other.Item4));
            }
        }  // internal class DeepCopyChecker

        private static readonly DeepCopyChecker DeepCopyCheckerInstance = (
            new DeepCopyChecker());

        private static bool SomethingShallowEquals(
            Our.Something that,
            Our.Something other)
        {
            return (
                that.Values == other.Values
                && that.TupleWithJson == other.TupleWithJson);
        }

        [Test]
        public void Test_Something_shallow_copy()
        {
            Our.Something instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Our.Copying.Shallow(instance);

            Assert.IsTrue(
                SomethingShallowEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_shallow_copy

        [Test]
        public void Test_Something_deep_copy()
        {
            Our.Something instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Our.Copying.Deep(instance);

            Assert.IsTrue(
                DeepCopyCheckerInstance.Transform(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_deep_copy
    }  // class TestCopying
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
