/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Our = dummy;  // renamed
using System.Collections.Generic;  // can't alias
using System.Linq;  // can't alias

namespace dummy
{
    /// <summary>
    /// Allow for enhancing of our model classes with custom wraps.
    /// </summary>
    public static class Enhancing
    {
        public abstract class Enhanced<TEnhancement> where TEnhancement : class
        {
            // ReSharper disable once InconsistentNaming
            protected readonly TEnhancement _enhancement;

            protected Enhanced(TEnhancement enhancement)
            {
                _enhancement = enhancement;
            }

            internal TEnhancement _getEnhancement()
            {
                return _enhancement;
            }
        }

        public class EnhancedSomething<TEnhancement>
            : Enhanced<TEnhancement>, Our.ISomething
            where TEnhancement : class
        {
            private readonly Our.ISomething _instance;

            public EnhancedSomething(
                Our.ISomething instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public string Text
            {
                get => _instance.Text;
                set => _instance.Text = value;
            }

            public long Number
            {
                get => _instance.Number;
                set => _instance.Number = value;
            }

            public Kind Kind
            {
                get => _instance.Kind;
                set => _instance.Kind = value;
            }

            public List<string> Texts
            {
                get => _instance.Texts;
                set => _instance.Texts = value;
            }

            public List<long> Numbers
            {
                get => _instance.Numbers;
                set => _instance.Numbers = value;
            }

            public List<Kind> Kinds
            {
                get => _instance.Kinds;
                set => _instance.Kinds = value;
            }

            public List<string> Codes
            {
                get => _instance.Codes;
                set => _instance.Codes = value;
            }

            public List<bool> Flags
            {
                get => _instance.Flags;
                set => _instance.Flags = value;
            }

            public List<string>? OptionalTexts
            {
                get => _instance.OptionalTexts;
                set => _instance.OptionalTexts = value;
            }

            public Kind? OptionalKind
            {
                get => _instance.OptionalKind;
                set => _instance.OptionalKind = value;
            }

            public IEnumerable<string> OverOptionalTextsOrEmpty()
            {
                return _instance.OverOptionalTextsOrEmpty();
            }

            public bool OptionalTextsAreUniqueIgnoring(
                HashSet<string> ignored
            )
            {
                return _instance.OptionalTextsAreUniqueIgnoring(
                    ignored
                );
            }

            public IEnumerable<Our.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Our.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Our.Visitation.IVisitor visitor)
            {
                visitor.VisitSomething(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitSomething(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformSomething(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformSomething(_instance, context);
            }
        }

        public class EnhancedCollection<TEnhancement>
            : Enhanced<TEnhancement>, Our.ICollection
            where TEnhancement : class
        {
            private readonly Our.ICollection _instance;

            public EnhancedCollection(
                Our.ICollection instance,
                TEnhancement enhancement
            ) : base(enhancement)
            {
                _instance = instance;
            }

            public HashSet<string> Texts
            {
                get => _instance.Texts;
                set => _instance.Texts = value;
            }

            public HashSet<long> Numbers
            {
                get => _instance.Numbers;
                set => _instance.Numbers = value;
            }

            public HashSet<bool> Flags
            {
                get => _instance.Flags;
                set => _instance.Flags = value;
            }

            public HashSet<Direction> Directions
            {
                get => _instance.Directions;
                set => _instance.Directions = value;
            }

            public HashSet<string> Codes
            {
                get => _instance.Codes;
                set => _instance.Codes = value;
            }

            public HashSet<string>? OptionalTexts
            {
                get => _instance.OptionalTexts;
                set => _instance.OptionalTexts = value;
            }

            public HashSet<Direction>? OptionalDirections
            {
                get => _instance.OptionalDirections;
                set => _instance.OptionalDirections = value;
            }

            public IEnumerable<string> OverOptionalTextsOrEmpty()
            {
                return _instance.OverOptionalTextsOrEmpty();
            }

            public IEnumerable<Our.Direction> OverOptionalDirectionsOrEmpty()
            {
                return _instance.OverOptionalDirectionsOrEmpty();
            }

            public bool TextsAreNotAllIn(
                HashSet<string> others
            )
            {
                return _instance.TextsAreNotAllIn(
                    others
                );
            }

            public IEnumerable<Our.IClass> DescendOnce()
            {
                return _instance.DescendOnce();
            }

            public IEnumerable<Our.IClass> Descend()
            {
                return _instance.Descend();
            }

            public void Accept(Our.Visitation.IVisitor visitor)
            {
                visitor.VisitCollection(_instance);
            }

            public void Accept<TContext>(
                Visitation.IVisitorWithContext<TContext> visitor,
                TContext context
            )
            {
                visitor.VisitCollection(_instance, context);
            }

            public T Transform<T>(Visitation.ITransformer<T> transformer)
            {
                return transformer.TransformCollection(_instance);
            }

            public T Transform<TContext, T>(
                Visitation.ITransformerWithContext<TContext, T> transformer,
                TContext context
            )
            {
                return transformer.TransformCollection(_instance, context);
            }
        }

        internal class Wrapper<TEnhancement>
            : Our.Visitation.AbstractTransformer<Our.IClass>
            where TEnhancement : class
        {
            private readonly System.Func<Our.IClass, TEnhancement?> _enhancementFactory;

            internal Wrapper(
                System.Func<Our.IClass, TEnhancement?> enhancementFactory
            )
            {
                _enhancementFactory = enhancementFactory;
            }

            public override Our.IClass TransformSomething(
                Our.ISomething that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedSomething<TEnhancement>(
                        that,
                        enhancement
                    );
            }

            public override Our.IClass TransformCollection(
                Our.ICollection that
            )
            {
                if (that is Enhanced<TEnhancement>)
                {
                    throw new System.ArgumentException(
                        $"The instance has been already enhanced: {that}"
                    );
                }

                var enhancement = _enhancementFactory(that);
                return (enhancement == null)
                    ? that
                    : new EnhancedCollection<TEnhancement>(
                        that,
                        enhancement
                    );
            }
        }

        /// <summary>
        /// Unwrap enhancements from the wrapped instances.
        /// </summary>
        /// <typeparam name="TEnhancement">type of the enhancement</typeparam>
        public class Unwrapper<TEnhancement> where TEnhancement : class
        {
            /// <summary>
            /// Unwrap the given model instance.
            /// </summary>
            /// <param name="that">model instance to be unwrapped</param>
            /// <returns>
            /// Enhancement, or <c>null</c> if <paramref name="that" />
            /// has not been wrapped yet.
            /// </returns>
            public TEnhancement? Unwrap(Our.IClass that)
            {
                // ReSharper disable once SuspiciousTypeConversion.Global
                var enhanced = that as Enhanced<TEnhancement>;
                return enhanced?._getEnhancement();
            }

            /// <summary>
            /// Unwrap the given model instance.
            /// </summary>
            /// <param name="that">model instance to be unwrapped</param>
            /// <returns>
            /// Enhancement wrapped around <paramref name="that" />
            /// </returns>
            /// <exception cref="System.ArgumentException">
            /// Thrown when <paramref name="that" /> has not been wrapped yet
            /// </exception>
            public TEnhancement MustUnwrap(Our.IClass that)
            {
                return Unwrap(that) ?? throw new System.ArgumentException(
                    $"Expected the instance to have been wrapped, but it was not: {that}"
                );
            }
        }  // public class Unwrapper

        /// <summary>
        /// Wrap and unwrap the instances of model classes with enhancement.
        /// </summary>
        /// <typeparam name="TEnhancement">type of the enhancement</typeparam>
        public class Enhancer<TEnhancement>
            : Unwrapper<TEnhancement>
            where TEnhancement : class
        {
            private readonly Wrapper<TEnhancement> _wrapper;

            /// <param name="enhancementFactory">
            /// <para>how to enhance the instances.</para>
            ///
            /// <para>If it returns <c>null</c>, the instance will not be wrapped. However,
            /// the wrapping will continue recursively.</para>
            ///</param>
            public Enhancer(
                System.Func<Our.IClass, TEnhancement?> enhancementFactory
            )
            {
                _wrapper = new Wrapper<TEnhancement>(enhancementFactory);
            }

            /// <summary>
            /// Wrap the instance with an enhancement.
            /// </summary>
            /// <remarks>
            /// Double wraps are not allowed to prevent runtime leakage.
            ///
            /// If you use references to the instance objects, you have to update them
            /// after the wrapping, as the wrapping is recursive.
            /// </remarks>
            /// <param name="that">model instance to be wrapped</param>
            /// <returns>
            /// <paramref name="that" /> instance wrapped recursively with enhancements
            /// </returns>
            /// <exception cref="System.ArgumentException">
            /// Thrown when <paramref name="that" /> has been already wrapped
            /// </exception>
            public Our.IClass Wrap(
                Our.IClass that
            )
            {
                var wrapped = _wrapper.Transform(that);
                return (
                    wrapped
                ) ?? throw new System.InvalidOperationException(
                    "Expected the wrapped instance to be an instance of IClass, " +
                    $"but got: {wrapped}"
                );
            }
        }  // public class Enhancer
    }  // public static class Enhancing
}  // namespace dummy

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
