/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Our = dummy;  // renamed

// We need to use System.MemoryExtension.SequenceEqual.
using System;  // can't alias
using System.Collections.Generic;  // can't alias

using NUnit.Framework;  // can't alias

namespace dummy.Tests
{
    public class TestCopying
    {
        /// <summary>
        /// Check that the context is a deep copy of the visited instance.
        /// </summary>
        /// <remarks>
        /// The copy has to equal the original by value, while it must share none
        /// of the mutable objects with it.
        /// </remarks>
        internal class DeepCopyChecker
            : Our.Visitation.AbstractTransformerWithContext<Our.IClass, bool>
        {
            private static bool BytesEqualButDistinct(
                byte[] that,
                byte[] other)
            {
                // NOTE (mristin):
                // A byte[] implicitly converts to a ReadOnlySpan, which compares by content.
                // See: https://stackoverflow.com/a/48599119/1600678
                return (
                    !ReferenceEquals(that, other)
                    && ((System.ReadOnlySpan<byte>)that).SequenceEqual(other));
            }

            public override bool TransformSomeItem(
                Our.ISomeItem that,
                Our.IClass other)
            {
                if (!(other is Our.SomeItem casted) || ReferenceEquals(that, other))
                {
                    return false;
                }

                return (
                    that.Name == casted.Name);
            }

            public override bool TransformAnotherItem(
                Our.IAnotherItem that,
                Our.IClass other)
            {
                if (!(other is Our.AnotherItem casted) || ReferenceEquals(that, other))
                {
                    return false;
                }

                return (
                    that.SerialNumber == casted.SerialNumber);
            }

            public override bool TransformSimple(
                Our.ISimple that,
                Our.IClass other)
            {
                if (!(other is Our.Simple casted) || ReferenceEquals(that, other))
                {
                    return false;
                }

                return (
                    that.Name == casted.Name);
            }

            public override bool TransformSomething(
                Our.ISomething that,
                Our.IClass other)
            {
                if (!(other is Our.Something casted) || ReferenceEquals(that, other))
                {
                    return false;
                }

                return (
                    Transform(
                        that.Item,
                        casted.Item)
                    && Check_ListOf_IAbstractItem(
                        that.SomeItems,
                        casted.SomeItems)
                    && Check_ListOf_ISimple(
                        that.SomeSimples,
                        casted.SomeSimples));
            }

            private bool Check_ListOf_IAbstractItem(
                List<Our.IAbstractItem> that,
                List<Our.IAbstractItem> other)
            {
                if (ReferenceEquals(that, other) || that.Count != other.Count)
                {
                    return false;
                }

                for (int i = 0; i < that.Count; i++)
                {
                    if (!(
                        Transform(
                            that[i],
                            other[i])))
                    {
                        return false;
                    }
                }

                return true;
            }

            private bool Check_ListOf_ISimple(
                List<Our.ISimple> that,
                List<Our.ISimple> other)
            {
                if (ReferenceEquals(that, other) || that.Count != other.Count)
                {
                    return false;
                }

                for (int i = 0; i < that.Count; i++)
                {
                    if (!(
                        Transform(
                            that[i],
                            other[i])))
                    {
                        return false;
                    }
                }

                return true;
            }
        }  // internal class DeepCopyChecker

        private static readonly DeepCopyChecker DeepCopyCheckerInstance = (
            new DeepCopyChecker());

        private static bool SomeItemShallowEquals(
            Our.SomeItem that,
            Our.SomeItem other)
        {
            return that.Name == other.Name;
        }

        private static bool AnotherItemShallowEquals(
            Our.AnotherItem that,
            Our.AnotherItem other)
        {
            return that.SerialNumber == other.SerialNumber;
        }

        private static bool SimpleShallowEquals(
            Our.Simple that,
            Our.Simple other)
        {
            return that.Name == other.Name;
        }

        private static bool SomethingShallowEquals(
            Our.Something that,
            Our.Something other)
        {
            return (
                that.Item == other.Item
                && that.SomeItems == other.SomeItems
                && that.SomeSimples == other.SomeSimples);
        }

        [Test]
        public void Test_SomeItem_shallow_copy()
        {
            Our.SomeItem instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomeItem());

            var instanceCopy = Our.Copying.Shallow(instance);

            Assert.IsTrue(
                SomeItemShallowEquals(
                    instance, instanceCopy),
                "SomeItem");
        }  // public void Test_SomeItem_shallow_copy

        [Test]
        public void Test_SomeItem_deep_copy()
        {
            Our.SomeItem instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomeItem());

            var instanceCopy = Our.Copying.Deep(instance);

            Assert.IsTrue(
                DeepCopyCheckerInstance.Transform(
                    instance, instanceCopy),
                "SomeItem");
        }  // public void Test_SomeItem_deep_copy

        [Test]
        public void Test_AnotherItem_shallow_copy()
        {
            Our.AnotherItem instance = (
                Our.Tests.CommonJsonization.LoadMaximalAnotherItem());

            var instanceCopy = Our.Copying.Shallow(instance);

            Assert.IsTrue(
                AnotherItemShallowEquals(
                    instance, instanceCopy),
                "AnotherItem");
        }  // public void Test_AnotherItem_shallow_copy

        [Test]
        public void Test_AnotherItem_deep_copy()
        {
            Our.AnotherItem instance = (
                Our.Tests.CommonJsonization.LoadMaximalAnotherItem());

            var instanceCopy = Our.Copying.Deep(instance);

            Assert.IsTrue(
                DeepCopyCheckerInstance.Transform(
                    instance, instanceCopy),
                "AnotherItem");
        }  // public void Test_AnotherItem_deep_copy

        [Test]
        public void Test_Simple_shallow_copy()
        {
            Our.Simple instance = (
                Our.Tests.CommonJsonization.LoadMaximalSimple());

            var instanceCopy = Our.Copying.Shallow(instance);

            Assert.IsTrue(
                SimpleShallowEquals(
                    instance, instanceCopy),
                "Simple");
        }  // public void Test_Simple_shallow_copy

        [Test]
        public void Test_Simple_deep_copy()
        {
            Our.Simple instance = (
                Our.Tests.CommonJsonization.LoadMaximalSimple());

            var instanceCopy = Our.Copying.Deep(instance);

            Assert.IsTrue(
                DeepCopyCheckerInstance.Transform(
                    instance, instanceCopy),
                "Simple");
        }  // public void Test_Simple_deep_copy

        [Test]
        public void Test_Something_shallow_copy()
        {
            Our.Something instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Our.Copying.Shallow(instance);

            Assert.IsTrue(
                SomethingShallowEquals(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_shallow_copy

        [Test]
        public void Test_Something_deep_copy()
        {
            Our.Something instance = (
                Our.Tests.CommonJsonization.LoadMaximalSomething());

            var instanceCopy = Our.Copying.Deep(instance);

            Assert.IsTrue(
                DeepCopyCheckerInstance.Transform(
                    instance, instanceCopy),
                "Something");
        }  // public void Test_Something_deep_copy
    }  // class TestCopying
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
