/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.types.model;

import dummy.common.*;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;
import java.util.List;
import dummy.types.model.IClass;
import java.util.Optional;

public interface IItem extends IClass {
  String getNumber();

  void setNumber(String number);

  String getCode();

  void setCode(String code);

  /**
   * Render a human-readable description of the item.
   */
  String describe();
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
