/**
 * Test XML de/serialization of interfaces.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasXmlization from "../src/xmlization";
import * as AasTypes from "../src/types";

import * as TestCommonXmlization from "./commonXmlization";

test(
  "IHasSemantics XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasSemantics XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasSemantics(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IHasSemantics XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IHasExtensions XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from AssetAdministrationShell OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAssetAdministrationShell();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from ConceptDescription OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalConceptDescription();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasExtensions XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasExtensions(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IHasExtensions XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IReferable XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from AssetAdministrationShell OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAssetAdministrationShell();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from ConceptDescription OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalConceptDescription();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IReferable XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asReferable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IReferable XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IIdentifiable XML round-trip " +
  "starting from AssetAdministrationShell OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAssetAdministrationShell();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asIdentifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IIdentifiable XML round-trip " +
  "starting from ConceptDescription OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalConceptDescription();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asIdentifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IIdentifiable XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asIdentifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IIdentifiable XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IHasKind XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasKind(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IHasKind XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IHasDataSpecification XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from AssetAdministrationShell OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAssetAdministrationShell();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from ConceptDescription OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalConceptDescription();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IHasDataSpecification XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asHasDataSpecification(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IHasDataSpecification XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IQualifiable XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from Submodel OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodel();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IQualifiable XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asQualifiable(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IQualifiable XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "ISubmodelElement XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Capability OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalCapability();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Entity OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalEntity();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Operation OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalOperation();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from SubmodelElementCollection OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementCollection();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "ISubmodelElement XML round-trip " +
  "starting from SubmodelElementList OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalSubmodelElementList();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asSubmodelElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("ISubmodelElement XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IRelationshipElement XML round-trip " +
  "starting from AnnotatedRelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalAnnotatedRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asRelationshipElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IRelationshipElement XML round-trip " +
  "starting from RelationshipElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRelationshipElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asRelationshipElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IRelationshipElement XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IDataElement XML round-trip " +
  "starting from Blob OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBlob();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IDataElement XML round-trip " +
  "starting from File OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalFile();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IDataElement XML round-trip " +
  "starting from MultiLanguageProperty OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalMultiLanguageProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IDataElement XML round-trip " +
  "starting from Property OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalProperty();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IDataElement XML round-trip " +
  "starting from Range OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalRange();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test(
  "IDataElement XML round-trip " +
  "starting from ReferenceElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalReferenceElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IDataElement XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IEventElement XML round-trip " +
  "starting from BasicEventElement OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalBasicEventElement();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asEventElement(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IEventElement XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test("IAbstractLangString XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

test(
  "IDataSpecificationContent XML round-trip " +
  "starting from DataSpecificationIec61360 OK",
  () => {
    const instance = TestCommonXmlization.loadMinimalDataSpecificationIec61360();

    const xmlText = AasXmlization.toXmlString(instance);
    const anotherInstanceOrError = AasXmlization.fromXmlString(xmlText);
    expect(anotherInstanceOrError.error).toBeNull();
    const anotherInstance = anotherInstanceOrError.mustValue();

    const asInterface = AasTypes.asDataSpecificationContent(anotherInstance);
    expect(asInterface).not.toBeNull();
  }
);

test("IDataSpecificationContent XML deserialization fail", () => {
  const instanceOrError = AasXmlization.fromXmlString("This is not XML.");
  expect(instanceOrError.error).not.toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
