/**
 * Test basic XMLization helper classes and malformed XML inputs.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasXmlization from "../src/xmlization";

test("xmlization path renders as a relative XPath", () => {
  const path = new AasXmlization.Path();

  path.prepend(new AasXmlization.IndexSegment(3));
  path.prepend(new AasXmlization.ElementSegment("something"));

  expect(path.toString()).toStrictEqual("something/*[3]");
});

test("xmlization key segment renders as a predicate on the name", () => {
  const path = new AasXmlization.Path();

  path.prepend(new AasXmlization.ElementSegment("value"));
  path.prepend(new AasXmlization.KeySegment("a \"tricky\" <key>"));
  path.prepend(new AasXmlization.ElementSegment("struct"));

  expect(path.toString()).toStrictEqual(
    "struct/member[name=\"a &quot;tricky&quot; &lt;key&gt;\"]/value"
  );
});

test("xmlization errors default to empty path", () => {
  const deserializationError = new AasXmlization.DeserializationError("broken XML");
  expect(deserializationError.message).toStrictEqual("broken XML");
  expect(deserializationError.path.toString()).toStrictEqual("");

  const serializationError = new AasXmlization.SerializationError("broken object graph");
  expect(serializationError.message).toStrictEqual("broken object graph");
  expect(serializationError.path).toStrictEqual("");
});

test("xmlization serialization path renders as an access expression", () => {
  const error = new AasXmlization.SerializationError("broken object graph");

  error.prependKey("a b");
  error.prependIndex(3);
  error.prependProperty("something");

  expect(error.path).toStrictEqual('.something[3]["a b"]');
});

test("xmlization fails on malformed XML", () => {
  const malformedXml = "<something><notClosed>";
  const instanceOrError = AasXmlization.fromXmlString(malformedXml);
  expect(instanceOrError.error).not.toBeNull();
});

test("xmlization fails on empty XML", () => {
  const instanceOrError = AasXmlization.fromXmlString("");
  expect(instanceOrError.error).not.toBeNull();
});

test("xmlization fails on non-XML text", () => {
  const instanceOrError = AasXmlization.fromXmlString("Definitely not XML");
  expect(instanceOrError.error).not.toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
