/*
 * This code has been automatically generated by aas-core-csharp-codegen.
 * Do NOT edit or append.
 */

/*
 * We implement a streaming-based XML de/serialization with 
 * <see cref="System.Xml.XmlReader" /> and <see cref="System.Xml.XmlWriter" /> 
 * due to performance reasons.
 * For more information, see:
 * <ul>
 * <li>https://bertwagner.com/posts/xmlreader-vs-xmldocument-performance/</li>
 * <li>https://www.erikthecoder.net/2019/08/02/xml-parsing-performance-csharp-versus-go/</li>
 * <li>https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-serializer-generator-tool-sgen-exe</li>
 * </ul>
 */

using Xml = System.Xml;
using System.Collections.Generic;  // can't alias

using Aas = AasCore.Aas3;
using Visitation = AasCore.Aas3.Visitation;

namespace AasCore.Aas3
{
    public static class Xmlization
    {
        public class Serializer : Visitation.Visitor 
        {    private readonly Xml.XmlWriter _writer;

            Serializer(Xml.XmlWriter writer)
            {
                _writer = writer;
            }

            public void Visit(IEntity that)
            {
                that.Accept(this);
            }

            public void Visit(LangString that) 
            {
                _writer.WriteStartElement("langString");
                _writer.WriteAttributeString(
                    null, "language", null, that.Language);
                _writer.WriteValue(that.Text);
                _writer.WriteEndElement();
            }

            public void Visit(Identifier that) 
            {
                _writer.WriteStartElement("identifier");
                string theIdType = Stringification.ToString(that.IdType)
                    ?? throw new System.ArgumentException(
                        $"Invalid IdentifierType: {that.IdType}");
                _writer.WriteAttributeString(
                    null, "idType", null, theIdType);
                _writer.WriteValue(that.Id);
                _writer.WriteEndElement();
            }

            public void Visit(AdministrativeInformation that) 
            {

            }

            public void Visit(Key that) 
            {
                _writer.WriteStartElement("key");
                string theType = Stringification.ToString(that.Type)
                    ?? throw new System.ArgumentException(
                        $"Invalid KeyElements: {that.Type}");
                _writer.WriteAttributeString(
                    null, "type", null, theType);
                string theIdType = Stringification.ToString(that.IdType)
                    ?? throw new System.ArgumentException(
                        $"Invalid KeyType: {that.IdType}");
                _writer.WriteAttributeString(
                    null, "idType", null, theIdType);
                _writer.WriteValue(that.Value);
                _writer.WriteEndElement();
            }

            public void Visit(Reference that) 
            {

            }

            public void Visit(AssetAdministrationShell that) 
            {

            }

            public void Visit(Environment that) 
            {

            }
        }  // public class Serializer
    }  // public static class Xmlization
}  // namespace AasCore.Aas3

/*
 * This code has been automatically generated by aas-core-csharp-codegen.
 * Do NOT edit or append.
 */
