/**
 * Test JSON de/serialization of interfaces.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as OurJsonization from "../src/jsonization";
import * as TestCommon from "./common";
import * as TestCommonJsonization from "./commonJsonization";

test(
  "IParent round-trip " +
  "starting from ChildA OK",
  () => {
  const instance = TestCommonJsonization.loadMinimalChildA();

  const jsonable = OurJsonization.toJsonable(instance);

  const anotherInstanceOrError = OurJsonization.parentFromJsonable(
    jsonable
  );
  expect(anotherInstanceOrError.error).toBeNull();
  const anotherInstance = anotherInstanceOrError.mustValue();

  const anotherJsonable = OurJsonization.toJsonable(anotherInstance);

  const inequalityError = TestCommon.checkJsonablesEqual(
    jsonable,
    anotherJsonable
  );
  if (inequalityError !== null) {
    throw new Error(
      "The minimal example of IParent " +
      "as an instance of ChildA serialized " +
      "to JSON, then de-serialized and serialized again does not match " +
      `the first JSON: ${inequalityError.path}: ${inequalityError.message}`
    );
  }
});

test(
  "IParent round-trip " +
  "starting from ChildB OK",
  () => {
  const instance = TestCommonJsonization.loadMinimalChildB();

  const jsonable = OurJsonization.toJsonable(instance);

  const anotherInstanceOrError = OurJsonization.parentFromJsonable(
    jsonable
  );
  expect(anotherInstanceOrError.error).toBeNull();
  const anotherInstance = anotherInstanceOrError.mustValue();

  const anotherJsonable = OurJsonization.toJsonable(anotherInstance);

  const inequalityError = TestCommon.checkJsonablesEqual(
    jsonable,
    anotherJsonable
  );
  if (inequalityError !== null) {
    throw new Error(
      "The minimal example of IParent " +
      "as an instance of ChildB serialized " +
      "to JSON, then de-serialized and serialized again does not match " +
      `the first JSON: ${inequalityError.path}: ${inequalityError.message}`
    );
  }
});

test(
  "IParent round-trip " +
  "starting from Container OK",
  () => {
  const instance = TestCommonJsonization.loadMinimalContainer();

  const jsonable = OurJsonization.toJsonable(instance);

  const anotherInstanceOrError = OurJsonization.parentFromJsonable(
    jsonable
  );
  expect(anotherInstanceOrError.error).toBeNull();
  const anotherInstance = anotherInstanceOrError.mustValue();

  const anotherJsonable = OurJsonization.toJsonable(anotherInstance);

  const inequalityError = TestCommon.checkJsonablesEqual(
    jsonable,
    anotherJsonable
  );
  if (inequalityError !== null) {
    throw new Error(
      "The minimal example of IParent " +
      "as an instance of Container serialized " +
      "to JSON, then de-serialized and serialized again does not match " +
      `the first JSON: ${inequalityError.path}: ${inequalityError.message}`
    );
  }
});

test("IParent deserialization fail", () => {
  const jsonable = "This is not a IParent.";

  const instanceOrError = OurJsonization.parentFromJsonable(
    jsonable
  );
  expect(instanceOrError.error.message).toStrictEqual(
    "Expected a JSON object, but got: string"
  );
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
