package jsonization_test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"testing"
	aasjsonization "github.com/dummy-works/dummy/jsonization"
	aastesting "github.com/dummy-works/dummy/aastesting"
)

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
