/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.enhancing;

import java.lang.Iterable;
import java.util.Optional;
import java.util.List;
import dummy.common.*;
import dummy.visitation.IVisitor;
import dummy.visitation.IVisitorWithContext;
import dummy.visitation.ITransformer;
import dummy.visitation.ITransformerWithContext;
import dummy.types.enums.*;
import dummy.types.impl.*;
import dummy.types.model.*;

public class EnhancedFirst<EnhancementT>
  extends Enhanced<EnhancementT>
  implements IFirst {
  private final IFirst instance;

  public EnhancedFirst(
    IFirst instance,
    EnhancementT enhancement
  ) {
    super(enhancement);
    this.instance = instance;
  }

  @Override
  public List<String> getTexts() {
    return instance.getTexts();
  }

  @Override
  public void setTexts(List<String> texts) {
    instance.setTexts(texts);
  }

  @Override
  public Long getCount() {
    return instance.getCount();
  }

  @Override
  public void setCount(Long count) {
    instance.setCount(count);
  }

  @Override
  public Optional<Kind> getKind() {
    return instance.getKind();
  }

  @Override
  public void setKind(Kind kind) {
    instance.setKind(kind);
  }

  public Boolean hasText(
    String text
  )
  {
    return instance.hasText(
      text
    );
  }

  public Long totalLength() {
    return instance.totalLength();
  }

  public Boolean isCountWithin(
    Long limit
  )
  {
    return instance.isCountWithin(
      limit
    );
  }

  public Boolean isCountBetween(
    Long low,
    Long high
  )
  {
    return instance.isCountBetween(
      low,
      high
    );
  }

  public Boolean isEmpty() {
    return instance.isEmpty();
  }

  public Long parity() {
    return instance.parity();
  }

  public void fillNumbers(
    List<Long> numbers
  )
  {
    instance.fillNumbers(
      numbers
    );
  }

  public void copyCountTo(
    IItem other
  )
  {
    instance.copyCountTo(
      other
    );
  }

  public void fillTexts(
    String text
  )
  {
    instance.fillTexts(
      text
    );
  }

  public void reset() {
    instance.reset();
  }

  public Long incrementCount() {
    return instance.incrementCount();
  }

  public Iterable<IClass> descendOnce() {
    return instance.descendOnce();
  }

  public Iterable<IClass> descend() {
    return instance.descend();
  }

  public void accept(IVisitor visitor) {
    visitor.visitFirst(instance);
  }

  public <ContextT> void accept(
    IVisitorWithContext<ContextT> visitor,
    ContextT context
  ) {
    visitor.visitFirst(instance, context);
  }

  public <T> T transform(ITransformer<T> transformer) {
    return transformer.transformFirst(instance);
  }

  public <ContextT, T> T transform(
    ITransformerWithContext<ContextT, T> transformer,
    ContextT context
  ) {
    return transformer.transformFirst(instance, context);
  }
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
