/**
 * Provide constant values of the meta-model.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

/* eslint-disable @typescript-eslint/no-unused-vars */

import * as AasTypes from "./types";

/* eslint-enable @typescript-eslint/no-unused-vars */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
