"""Provide constant values of the meta-model."""

# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.

import sys
from typing import AbstractSet

if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final

import dummy.types as our_types

#: List the texts which must not be used.
RESERVED_TEXTS: Final[AbstractSet[str]] = {
    'reserved',
    'forbidden'
}

#: List the numbers which bring luck.
LUCKY_NUMBERS: Final[AbstractSet[int]] = {
    7,
    42
}

#: List the special kinds.
SPECIAL_KINDS: Final[AbstractSet[our_types.Kind]] = {
    our_types.Kind.BETA,
    our_types.Kind.GAMMA
}

# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
