/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.visitation;

import aas_core.aas3_0.types.model.*;
import aas_core.aas3_0.visitation.IVisitorWithContext;

/**
 * Perform double-dispatch to visit the concrete instances
 * with context.
 *
 * @param <ContextT> structure of the context
 */
public abstract class AbstractVisitorWithContext<ContextT>
  implements IVisitorWithContext<ContextT>
{
  public void visit(IClass that, ContextT context)
  {
    that.accept(this, context);
  }
  public abstract void visitSomething(
    ISomething that,
    ContextT context
  );
}

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
