/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package dummy.tests;

import dummy.jsonization.Jsonization;
import dummy.types.impl.*;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Provide methods to load instances from JSON test data.
 */
public final class CommonJsonization {
  public static Something loadMaximalSomething() throws IOException {
    final Path path = Paths.get(
      Common.TEST_DATA_DIR,
      "Json",
      "Expected",
      "Something",
      "maximal.json");

    final JsonNode node = CommonJson.readFromFile(path);

    return Jsonization.Deserialize.deserializeSomething(node);
  } // public static Something loadMaximalSomething

  public static Something loadMinimalSomething() throws IOException {
    final Path path = Paths.get(
      Common.TEST_DATA_DIR,
      "Json",
      "Expected",
      "Something",
      "minimal.json");

    final JsonNode node = CommonJson.readFromFile(path);

    return Jsonization.Deserialize.deserializeSomething(node);
  } // public static Something loadMinimalSomething
} // class CommonJsonization

// package dummy.tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
