/**
 * Check the transpilation of the `assert` statements.
 *
 * @remarks
 * The assertions hold for all the instances, valid or invalid, as the invariants
 * check their preconditions first. Hence, the generated SDKs never throw.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

/**
 * Represent runtime model type of an instance.
 */
export enum ModelType {
  ChildA = 0,
  ChildB = 1,
  Something = 2
}

/**
 * Iterate over the literals of {@link ModelType}.
 *
 * @remark
 * TypeScript does not provide an elegant way to iterate over the literals, so
 * this function helps you avoid common errors and pitfalls.
 *
 * @return iterator over the literals
 */
export function *overModelType (
): Iterable<ModelType> {
  // NOTE (mristin):
  // We yield numbers instead of literals to avoid name lookups on platforms
  // which do not provide JIT compilation of hot paths.
  yield <ModelType>0;  // ChildA
  yield <ModelType>1;  // ChildB
  yield <ModelType>2;  // Something
}

/**
 * Represent the most general class of the meta-model.
 */
export abstract class Class {
  /**
   * Indicate the runtime model type of an instance.
   */
  abstract modelType(): ModelType;

  /**
   * Iterate over all the instances referenced from this one.
   */
  abstract descendOnce(): IterableIterator<Class>;

  /**
   * Iterate recursively over all the instances referenced from this one.
   */
  abstract descend(): IterableIterator<Class>;

  /**
   * Dispatch the `visitor` on this instance.
   *
   * @param visitor - to be dispatched
   */
  abstract accept(visitor: AbstractVisitor): void;

  /**
   * Dispatch the `visitor` on this instance with `context`.
   *
   * @param visitor - to be dispatched
   * @param context - of the visitation
   * @typeParam ContextT - type of the visitation context
   */
  abstract acceptWithContext<ContextT>(
    visitor: AbstractVisitorWithContext<ContextT>,
    context: ContextT
  ): void;

  /**
   * Dispatch the `transformer` on this instance.
   *
   * @param transformer - to be dispatched
   * @return this instance transformed
   * @typeParam T - type of the transformation result
   */
  abstract transform<T>(transformer: AbstractTransformer<T>): T;

  /**
   * Dispatch the `transformer` on this instance in `context`.
   *
   * @param transformer - to be dispatched
   * @param context - of the transformation
   * @return this instance transformed
   * @typeParam T - type of the transformation result
   */
  abstract transformWithContext<ContextT, T>(
    transformer: AbstractTransformerWithContext<ContextT, T>,
    context: ContextT
  ): T;
}

export interface IParent extends Class {
  number: number;
}

export class ChildA
  extends Class
  implements IParent {
  /**
   * Indicate the runtime model type of the instance.
   */
  modelType(): ModelType {
    // NOTE (mristin):
    // We yield numbers instead of literals to avoid name lookups on platforms
    // which do not provide JIT compilation of hot paths.
    return <ModelType>0;  // ChildA
  }

  number: number;

  aOnly: number;

  /**
   * Iterate over the instances referenced from this instance.
   *
   * We do not recurse into the referenced instances.
   *
   * @returns Iterator over the referenced instances
   */
  *descendOnce(): IterableIterator<Class> {
    // No descendable properties
  }

  /**
   * Iterate recursively over the instances referenced from this instance.
   *
   * @returns Iterator over the referenced instances
   */
  *descend(): IterableIterator<Class> {
    // No descendable properties
  }

  /**
   * Dispatch `visitor` on this instance.
   *
   * @param visitor - to visit this instance
   */
  accept(visitor: AbstractVisitor): void {
    visitor.visitChildA(this);
  }

  /**
   * Dispatch `visitor` with `context` on this instance.
   *
   * @param visitor - to visit this instance
   * @param context - to be passed along to the dispatched visitor method
   * @typeParam ContextT - type of the context
   */
  acceptWithContext<ContextT>(
    visitor: AbstractVisitorWithContext<ContextT>,
    context: ContextT
  ) {
    visitor.visitChildAWithContext(this, context);
  }

  /**
   * Dispatch the `transformer` on this instance.
   *
   * @param transformer - to transform this instance
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   */
  transform<T>(transformer: AbstractTransformer<T>): T {
    return transformer.transformChildA(this);
  }

  /**
   * Dispatch the `transformer` on this instance in `context`.
   *
   * @param transformer - to transform this instance
   * @param context - to be passed along to the `transformer`
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   * @paramType ContextT - type of the transformation context
   */
  transformWithContext<ContextT, T>(
    transformer: AbstractTransformerWithContext<ContextT, T>,
    context: ContextT
  ): T {
    return transformer.transformChildAWithContext(
      this, context
    );
  }

  constructor(
    number: number,
    aOnly: number
  ) {
    super();
    this.number = number;
    this.aOnly = aOnly;
  }
}

export class ChildB
  extends Class
  implements IParent {
  /**
   * Indicate the runtime model type of the instance.
   */
  modelType(): ModelType {
    // NOTE (mristin):
    // We yield numbers instead of literals to avoid name lookups on platforms
    // which do not provide JIT compilation of hot paths.
    return <ModelType>1;  // ChildB
  }

  number: number;

  /**
   * Iterate over the instances referenced from this instance.
   *
   * We do not recurse into the referenced instances.
   *
   * @returns Iterator over the referenced instances
   */
  *descendOnce(): IterableIterator<Class> {
    // No descendable properties
  }

  /**
   * Iterate recursively over the instances referenced from this instance.
   *
   * @returns Iterator over the referenced instances
   */
  *descend(): IterableIterator<Class> {
    // No descendable properties
  }

  /**
   * Dispatch `visitor` on this instance.
   *
   * @param visitor - to visit this instance
   */
  accept(visitor: AbstractVisitor): void {
    visitor.visitChildB(this);
  }

  /**
   * Dispatch `visitor` with `context` on this instance.
   *
   * @param visitor - to visit this instance
   * @param context - to be passed along to the dispatched visitor method
   * @typeParam ContextT - type of the context
   */
  acceptWithContext<ContextT>(
    visitor: AbstractVisitorWithContext<ContextT>,
    context: ContextT
  ) {
    visitor.visitChildBWithContext(this, context);
  }

  /**
   * Dispatch the `transformer` on this instance.
   *
   * @param transformer - to transform this instance
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   */
  transform<T>(transformer: AbstractTransformer<T>): T {
    return transformer.transformChildB(this);
  }

  /**
   * Dispatch the `transformer` on this instance in `context`.
   *
   * @param transformer - to transform this instance
   * @param context - to be passed along to the `transformer`
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   * @paramType ContextT - type of the transformation context
   */
  transformWithContext<ContextT, T>(
    transformer: AbstractTransformerWithContext<ContextT, T>,
    context: ContextT
  ): T {
    return transformer.transformChildBWithContext(
      this, context
    );
  }

  constructor(number: number) {
    super();
    this.number = number;
  }
}

export class Something extends Class {
  /**
   * Indicate the runtime model type of the instance.
   */
  modelType(): ModelType {
    // NOTE (mristin):
    // We yield numbers instead of literals to avoid name lookups on platforms
    // which do not provide JIT compilation of hot paths.
    return <ModelType>2;  // Something
  }

  number: number;

  text: string;

  texts: Array<string>;

  parent: IParent;

  optionalText: string | null;

  /**
   * Check the assertion in a method.
   */
  doubledNumber(): number {
    const doubled = this.number + this.number;
    if (!((doubled - this.number) == (this.number))) {
      throw new Error(
        "Doubling must be reversible"
      );
    }
    return doubled;
  }

  /**
   * Iterate over the instances referenced from this instance.
   *
   * We do not recurse into the referenced instances.
   *
   * @returns Iterator over the referenced instances
   */
  *descendOnce(): IterableIterator<Class> {
    yield this.parent;
  }

  /**
   * Iterate recursively over the instances referenced from this instance.
   *
   * @returns Iterator over the referenced instances
   */
  *descend(): IterableIterator<Class> {
    yield this.parent;

    yield * this.parent.descend();
  }

  /**
   * Dispatch `visitor` on this instance.
   *
   * @param visitor - to visit this instance
   */
  accept(visitor: AbstractVisitor): void {
    visitor.visitSomething(this);
  }

  /**
   * Dispatch `visitor` with `context` on this instance.
   *
   * @param visitor - to visit this instance
   * @param context - to be passed along to the dispatched visitor method
   * @typeParam ContextT - type of the context
   */
  acceptWithContext<ContextT>(
    visitor: AbstractVisitorWithContext<ContextT>,
    context: ContextT
  ) {
    visitor.visitSomethingWithContext(this, context);
  }

  /**
   * Dispatch the `transformer` on this instance.
   *
   * @param transformer - to transform this instance
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   */
  transform<T>(transformer: AbstractTransformer<T>): T {
    return transformer.transformSomething(this);
  }

  /**
   * Dispatch the `transformer` on this instance in `context`.
   *
   * @param transformer - to transform this instance
   * @param context - to be passed along to the `transformer`
   * @returns transformation of this instance
   * @paramType T - type of the transformation result
   * @paramType ContextT - type of the transformation context
   */
  transformWithContext<ContextT, T>(
    transformer: AbstractTransformerWithContext<ContextT, T>,
    context: ContextT
  ): T {
    return transformer.transformSomethingWithContext(
      this, context
    );
  }

  constructor(
    number: number,
    text: string,
    texts: Array<string>,
    parent: IParent,
    optionalText: string | null = null
  ) {
    super();
    this.number = number;
    this.text = text;
    this.texts = texts;
    this.parent = parent;
    this.optionalText = optionalText;
  }
}

/**
 * Visit the instances of the model.
 */
export abstract class AbstractVisitor {
  /**
   * Double-dispatch on `that`.
   */
  visit(that: Class): void {
    that.accept(this);
  }

  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  abstract visitChildA(
    that: ChildA
  ): void;

  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  abstract visitChildB(
    that: ChildB
  ): void;

  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  abstract visitSomething(
    that: Something
  ): void;
}

/**
 * Visit the instances of the model with context.
 *
 * @typeParam ContextT - type of the visitation context
 */
export abstract class AbstractVisitorWithContext<ContextT> {
  /**
   * Double-dispatch on `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  visitWithContext(
    that: Class,
    context: ContextT
  ): void {
    that.acceptWithContext(this, context);
  }

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  abstract visitChildAWithContext(
    that: ChildA,
    context: ContextT
  ): void;

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  abstract visitChildBWithContext(
    that: ChildB,
    context: ContextT
  ): void;

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  abstract visitSomethingWithContext(
    that: Something,
    context: ContextT
  ): void;
}

/**
 * Visit the instances of the model without action.
 *
 * @remarks
 * This visitor is not meant to be directly used. Instead, you usually
 * inherit from it, and implement only the relevant visit methods.
 */
export class PassThroughVisitor extends AbstractVisitor {
  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  visitChildA(
    that: ChildA
  ): void {
    for (const another of that.descendOnce()) {
      this.visit(another);
    }
  }

  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  visitChildB(
    that: ChildB
  ): void {
    for (const another of that.descendOnce()) {
      this.visit(another);
    }
  }

  /**
   * Visit `that`.
   *
   * @param that - instance to be visited
   */
  visitSomething(
    that: Something
  ): void {
    for (const another of that.descendOnce()) {
      this.visit(another);
    }
  }
}

/**
 * Visit the instances of the model without action and in context.
 *
 * @remarks
 * This visitor is not meant to be directly used. Instead, you usually
 * inherit from it, and implement only the relevant visit methods.
 */
export class PassThroughVisitorWithContext<ContextT>
    extends AbstractVisitorWithContext<ContextT> {
  /**
   * Double-dispatch on `that` in `context`.
   */
  visitWithContext(
    that: Class,
    context: ContextT
  ): void {
    that.acceptWithContext(this, context);
  }

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  visitChildAWithContext(
    that: ChildA,
    context: ContextT
  ): void {
    for (const another of that.descendOnce()) {
      this.visitWithContext(another, context);
    }
  }

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  visitChildBWithContext(
    that: ChildB,
    context: ContextT
  ): void {
    for (const another of that.descendOnce()) {
      this.visitWithContext(another, context);
    }
  }

  /**
   * Visit `that` in `context`.
   *
   * @param that - instance to be visited
   * @param context - of the visitation
   */
  visitSomethingWithContext(
    that: Something,
    context: ContextT
  ): void {
    for (const another of that.descendOnce()) {
      this.visitWithContext(another, context);
    }
  }
}

/**
 * Transform the instance of the model.
 *
 * @typeParam T - type of the transformation result
 */
export abstract class AbstractTransformer<T> {
  /**
   * Double-dispatch on `that`.
   */
  transform(that: Class): T {
    return that.transform(this);
  }

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  abstract transformChildA(
    that: ChildA
  ): T;

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  abstract transformChildB(
    that: ChildB
  ): T;

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  abstract transformSomething(
    that: Something
  ): T;
}

/**
 * Transform the instances of the model in context.
 *
 * @typeParam ContextT - type of the transformation context
 * @typeParam T - type of the transformation result
 */
export abstract class AbstractTransformerWithContext<ContextT, T> {
  /**
   * Double-dispatch on `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the transformation
   * @returns transformed `that`
   */
  transformWithContext(
    that: Class,
    context: ContextT
  ): T {
    return that.transformWithContext(this, context);
  }

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the transformation
   * @returns transformed `that`
   */
  abstract transformChildAWithContext(
    that: ChildA,
    context: ContextT
  ): T;

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the transformation
   * @returns transformed `that`
   */
  abstract transformChildBWithContext(
    that: ChildB,
    context: ContextT
  ): T;

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the transformation
   * @returns transformed `that`
   */
  abstract transformSomethingWithContext(
    that: Something,
    context: ContextT
  ): T;
}

/**
 * Transform the instances of the model.
 *
 * @remarks
 * If you do not override the transformation methods, they simply
 * return {@link defaultResult}.
 *
 * @typeParam T - type of the transformation result
 */
export class TransformerWithDefault<T> extends AbstractTransformer<T> {
  /**
   * Default value which is returned if no override of the transformation
   */
  defaultResult: T

  /**
   * Initialize with the given `default` value.
   *
   * @param defaultResult - returned if no override of the transformation
   */
  constructor(defaultResult: T) {
    super();
    this.defaultResult = defaultResult;
  }

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildA(
    that: ChildA
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildB(
    that: ChildB
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /**
   * Transform `that`.
   *
   * @param that - instance to be transformed
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformSomething(
    that: Something
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */
}

/**
 * Transform the instances of the model in context.
 *
 * @remarks
 * If you do not override the transformation methods, they simply
 * return {@link defaultResult}.
 *
 * @typeParam ContextT - type of the visitation context
 * @typeParam T - type of the transformation result
 */
export class TransformerWithDefaultAndContext<ContextT, T>
    extends AbstractTransformerWithContext<ContextT, T> {
  /**
   * Default value which is returned if no override of the transformation
   */
  defaultResult: T

  /**
   * Initialize with the given `default` value.
   *
   * @param defaultResult - returned if no override of the transformation
   */
  constructor(defaultResult: T) {
    super();
    this.defaultResult = defaultResult;
  }

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the visitation
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildAWithContext(
    that: ChildA,
    context: ContextT
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the visitation
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildBWithContext(
    that: ChildB,
    context: ContextT
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /**
   * Transform `that` in `context`.
   *
   * @param that - instance to be transformed
   * @param context - of the visitation
   * @returns transformed `that`
   */
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformSomethingWithContext(
    that: Something,
    context: ContextT
  ): T {
    return this.defaultResult;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */
}

/**
 * Try to cast an instance of the model to {@link IParent}.
 */
class AsParentTransformer
    extends AbstractTransformer<IParent | null> {
  transformChildA(
    that: ChildA
  ): IParent | null {
    return that as IParent;
  }

  transformChildB(
    that: ChildB
  ): IParent | null {
    return that as IParent;
  }

  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformSomething(
    that: Something
  ): IParent | null {
    return null;
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */
}

const AS_PARENT_TRANSFORMER =
  new AsParentTransformer();

/**
 * Try to cast `that` instance to
 * the interface {@link IParent}.
 *
 * @param that - instance to be casted
 * @returns - casted `that` if cast successful, or `null`
 */
export function asParent(
  that: Class
): IParent | null {
  return AS_PARENT_TRANSFORMER.transform(that);
}

/**
 * Check the type of `that` instance.
 *
 * @param that - instance to be type-checked
 * @returns `true` if the type check is successful
 */
export function isParent(
  that: Class
): that is IParent {
  return asParent(that) !== null;
}

/**
 * Try to cast `that` instance to
 * the class {@link ChildA}.
 *
 * @param that - instance to be casted
 * @returns - casted `that` if cast successful, or `null`
 */
export function asChildA(
  that: Class
): ChildA | null {
  return (that instanceof ChildA)
    ? <ChildA>that
    : null;
}

/**
 * Check the type of `that` instance.
 *
 * @param that - instance to be type-checked
 * @returns `true` if the type check is successful
 */
export function isChildA(
  that: Class
): that is ChildA {
  return that instanceof ChildA;
}

/**
 * Try to cast `that` instance to
 * the class {@link ChildB}.
 *
 * @param that - instance to be casted
 * @returns - casted `that` if cast successful, or `null`
 */
export function asChildB(
  that: Class
): ChildB | null {
  return (that instanceof ChildB)
    ? <ChildB>that
    : null;
}

/**
 * Check the type of `that` instance.
 *
 * @param that - instance to be type-checked
 * @returns `true` if the type check is successful
 */
export function isChildB(
  that: Class
): that is ChildB {
  return that instanceof ChildB;
}

/**
 * Try to cast `that` instance to
 * the class {@link Something}.
 *
 * @param that - instance to be casted
 * @returns - casted `that` if cast successful, or `null`
 */
export function asSomething(
  that: Class
): Something | null {
  return (that instanceof Something)
    ? <Something>that
    : null;
}

/**
 * Check the type of `that` instance.
 *
 * @param that - instance to be type-checked
 * @returns `true` if the type check is successful
 */
export function isSomething(
  that: Class
): that is Something {
  return that instanceof Something;
}

class TypeMatcher extends AbstractTransformerWithContext<
  Readonly<Class>,
  boolean
> {
  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildAWithContext(
    that: ChildA,
    other: Class
  ): boolean {
    return isChildA(other);
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformChildBWithContext(
    that: ChildB,
    other: Class
  ): boolean {
    return isChildB(other);
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */

  /* eslint-disable @typescript-eslint/no-unused-vars */
  transformSomethingWithContext(
    that: Something,
    other: Class
  ): boolean {
    return isSomething(other);
  }
  /* eslint-enable @typescript-eslint/no-unused-vars */
}

const TYPE_MATCHER = new TypeMatcher();

/**
 * Check whether the type of `that` matches the type of `other` instance.
 *
 * @remarks
 * We check with `is*` function. Hence, if the class of `other` is a subclass of
 * the class of `that`, we confirm the match.
 *
 * @param that - standard instance
 * @param other - instance whose type is compared against `that`
 */
export function typesMatch<ClassT extends Class>(
  that: ClassT,
  other: Class
): other is ClassT {
  return TYPE_MATCHER.transformWithContext(that, other);
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
