/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

package aas_core.aas3_0.tests;

import static org.junit.jupiter.api.Assertions.assertEquals;

import aas_core.aas3_0.reporting.*;
import aas_core.aas3_0.stringification.Stringification;
import aas_core.aas3_0.types.enums.*;
import aas_core.aas3_0.types.impl.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Optional;
import org.junit.jupiter.api.Test;

public class TestXOrDefault {
  private static void compareOrRerecordValue(Object value, Path expectedPath) throws IOException {
    final ObjectMapper objectMapper = new ObjectMapper();
    JsonNode got = CommonJson.toJson(value);

    if (Common.RECORD_MODE) {
      Files.createDirectories(expectedPath.getParent());
      Files.write(expectedPath, got.toString().getBytes());
    }
    else
    {
      if (!Files.exists(expectedPath)) {
        throw new FileNotFoundException(
          "The file with the recorded value does not exist: " + expectedPath + "; " +
          "maybe you want to set the environment variable " +
          Common.RECORD_MODE_ENVIRONMENT_VARIABLE_NAME + "?");
      }

      final JsonNode expected = objectMapper.readTree(expectedPath.toFile());
      assertEquals(objectMapper.readTree(expected.toString()), objectMapper.readTree(got.toString()));
    }
  }

  @Test
  public void testExtensionValueTypeOrDefaultNonDefault()
     throws IOException {
    Extension instance = CommonJsonization.loadMaximalExtension();

    final DataTypeDefXsd enumValue = instance.valueTypeOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Extension",
        "valueTypeOrDefault.non-default.json"));
  } // public void testExtensionvalueTypeOrDefaultNonDefault

  @Test
  public void testExtensionvalueTypeOrDefaultDefault()
     throws IOException {
    Extension instance = CommonJsonization.loadMinimalExtension();

    final DataTypeDefXsd enumValue = instance.valueTypeOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Extension",
        "valueTypeOrDefault.default.json"));
  } // public void testExtensionvalueTypeOrDefaultDefault

  @Test
  public void testQualifierKindOrDefaultNonDefault()
     throws IOException {
    Qualifier instance = CommonJsonization.loadMaximalQualifier();

    final QualifierKind enumValue = instance.kindOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Qualifier",
        "kindOrDefault.non-default.json"));
  } // public void testQualifierkindOrDefaultNonDefault

  @Test
  public void testQualifierkindOrDefaultDefault()
     throws IOException {
    Qualifier instance = CommonJsonization.loadMinimalQualifier();

    final QualifierKind enumValue = instance.kindOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Qualifier",
        "kindOrDefault.default.json"));
  } // public void testQualifierkindOrDefaultDefault

  @Test
  public void testSubmodelKindOrDefaultNonDefault()
     throws IOException {
    Submodel instance = CommonJsonization.loadMaximalSubmodel();

    final ModellingKind enumValue = instance.kindOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Submodel",
        "kindOrDefault.non-default.json"));
  } // public void testSubmodelkindOrDefaultNonDefault

  @Test
  public void testSubmodelkindOrDefaultDefault()
     throws IOException {
    Submodel instance = CommonJsonization.loadMinimalSubmodel();

    final ModellingKind enumValue = instance.kindOrDefault();
    if (enumValue == null) {
      throw new IllegalStateException("Failed to stringify the enum");
    }

    final Optional<String> valueOptional = Stringification.toString(enumValue);
    assertEquals(true, valueOptional.isPresent());
    final String value = valueOptional.get();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Submodel",
        "kindOrDefault.default.json"));
  } // public void testSubmodelkindOrDefaultDefault

  @Test
  public void testSubmodelElementListOrderRelevantOrDefaultNonDefault()
     throws IOException {
    SubmodelElementList instance = CommonJsonization.loadMaximalSubmodelElementList();

    final Object value = instance.orderRelevantOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "SubmodelElementList",
        "orderRelevantOrDefault.non-default.json"));
  } // public void testSubmodelElementListorderRelevantOrDefaultNonDefault

  @Test
  public void testSubmodelElementListorderRelevantOrDefaultDefault()
     throws IOException {
    SubmodelElementList instance = CommonJsonization.loadMinimalSubmodelElementList();

    final Object value = instance.orderRelevantOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "SubmodelElementList",
        "orderRelevantOrDefault.default.json"));
  } // public void testSubmodelElementListorderRelevantOrDefaultDefault

  @Test
  public void testPropertyCategoryOrDefaultNonDefault()
     throws IOException {
    Property instance = CommonJsonization.loadMaximalProperty();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Property",
        "categoryOrDefault.non-default.json"));
  } // public void testPropertycategoryOrDefaultNonDefault

  @Test
  public void testPropertycategoryOrDefaultDefault()
     throws IOException {
    Property instance = CommonJsonization.loadMinimalProperty();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Property",
        "categoryOrDefault.default.json"));
  } // public void testPropertycategoryOrDefaultDefault

  @Test
  public void testMultiLanguagePropertyCategoryOrDefaultNonDefault()
     throws IOException {
    MultiLanguageProperty instance = CommonJsonization.loadMaximalMultiLanguageProperty();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "MultiLanguageProperty",
        "categoryOrDefault.non-default.json"));
  } // public void testMultiLanguagePropertycategoryOrDefaultNonDefault

  @Test
  public void testMultiLanguagePropertycategoryOrDefaultDefault()
     throws IOException {
    MultiLanguageProperty instance = CommonJsonization.loadMinimalMultiLanguageProperty();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "MultiLanguageProperty",
        "categoryOrDefault.default.json"));
  } // public void testMultiLanguagePropertycategoryOrDefaultDefault

  @Test
  public void testRangeCategoryOrDefaultNonDefault()
     throws IOException {
    Range instance = CommonJsonization.loadMaximalRange();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Range",
        "categoryOrDefault.non-default.json"));
  } // public void testRangecategoryOrDefaultNonDefault

  @Test
  public void testRangecategoryOrDefaultDefault()
     throws IOException {
    Range instance = CommonJsonization.loadMinimalRange();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Range",
        "categoryOrDefault.default.json"));
  } // public void testRangecategoryOrDefaultDefault

  @Test
  public void testReferenceElementCategoryOrDefaultNonDefault()
     throws IOException {
    ReferenceElement instance = CommonJsonization.loadMaximalReferenceElement();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "ReferenceElement",
        "categoryOrDefault.non-default.json"));
  } // public void testReferenceElementcategoryOrDefaultNonDefault

  @Test
  public void testReferenceElementcategoryOrDefaultDefault()
     throws IOException {
    ReferenceElement instance = CommonJsonization.loadMinimalReferenceElement();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "ReferenceElement",
        "categoryOrDefault.default.json"));
  } // public void testReferenceElementcategoryOrDefaultDefault

  @Test
  public void testBlobCategoryOrDefaultNonDefault()
     throws IOException {
    Blob instance = CommonJsonization.loadMaximalBlob();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Blob",
        "categoryOrDefault.non-default.json"));
  } // public void testBlobcategoryOrDefaultNonDefault

  @Test
  public void testBlobcategoryOrDefaultDefault()
     throws IOException {
    Blob instance = CommonJsonization.loadMinimalBlob();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "Blob",
        "categoryOrDefault.default.json"));
  } // public void testBlobcategoryOrDefaultDefault

  @Test
  public void testFileCategoryOrDefaultNonDefault()
     throws IOException {
    File instance = CommonJsonization.loadMaximalFile();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "File",
        "categoryOrDefault.non-default.json"));
  } // public void testFilecategoryOrDefaultNonDefault

  @Test
  public void testFilecategoryOrDefaultDefault()
     throws IOException {
    File instance = CommonJsonization.loadMinimalFile();

    final Object value = instance.categoryOrDefault();

    compareOrRerecordValue(
      value,
      Paths.get(
        Common.TEST_DATA_DIR,
        "XOrDefault",
        "File",
        "categoryOrDefault.default.json"));
  } // public void testFilecategoryOrDefaultDefault
} // class TestXOrDefault

// package aas_core.aas3_0.tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
