/**
 * Verify that the instances of the meta-model satisfy the invariants.
 *
 * Here is an example how to verify an instance of {@link types.Item}:
 *
 * ```ts
 * import * as AasTypes from "@dummy-works/dummy/types";
 * import * as AasVerification from "@dummy-works/dummy/verification";
 *
 * const anInstance = new AasTypes.Item(
 *   // ... some constructor arguments ...
 * );
 *
 * for (const error of AasVerification.verify(anInstance)) {
 *   console.log(`${error.message} at: ${error.path}`);
 * }
 * ```
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasCommon from "./common";
import * as AasConstants from "./constants";
import * as AasTypes from "./types";

// The generated code might contain deliberately double negations. For example,
// when the constraint is formulated as a NAND and we check that the constraint
// is not fulfilled. Therefore, we disable this linting rule.
/* eslint no-extra-boolean-cast: 0 */

// NOTE (mristin):
// The SDK defines three of these path vocabularies: this one, the one in
// the `jsonization` module, and the one in the `xmlcommon` module. They look
// alike, and it is tempting to merge them, but they are not interchangeable.
//
// Each of them points into a different thing:
//
// * This one points into the instances which you built, so a property segment
//   holds a class of the meta-model.
// * The jsonization's points into the JSON-able structure being read or
//   written, so a property segment holds the JSON-able object instead: while
//   a document is being parsed, the instance which the property would belong
//   to does not exist yet.
// * The xmlcommon's points into the XML document, where there are no
//   properties at all, only elements, so it names an element instead. It is
//   also the only one whose segments carry no back-pointer, as the reading is
//   a single pass over a token stream and the element is gone by the time
//   the error comes back out.
//
// The three also render differently: a path into the instances is
// a TypeScript access expression, a path into a JSON-able structure starts at
// the root of the document and carries no leading dot, and a path into an XML
// document is a relative XPath.
//
// Merging them would mean either dropping the back-pointers, which have been
// part of the public API of this SDK since before these modules were split
// apart, or defining a single path over the union of all the segment kinds --
// in which case every consumer would have to handle segments which can never
// occur in its world. Three small vocabularies which each say exactly what
// they can say cost less than one large one which lies about its range.

/**
 * Represent a property access on a path to an erroneous value.
 */
export class PropertySegment {
  /**
   * Instance containing the property
   */
  readonly instance: AasTypes.Class;

  /**
   * Name of the property
   */
  readonly name: string;

  constructor(instance: AasTypes.Class, name: string) {
    this.instance = instance;
    this.name = name;
  }

  toString(): string {
    return `.${this.name}`;
  }
}

/**
 * Represent an index access on a path to an erroneous value.
 */
export class IndexSegment {
  /**
   * Sequence containing the item at {@link index}
   */
  readonly sequence: ReadonlyArray<unknown>;

  /**
   * Index of the item in the {@link sequence}
   */
  readonly index: number;

  constructor(sequence: ReadonlyArray<unknown>, index: number) {
    this.sequence = sequence;
    this.index = index;
  }

  toString(): string {
    return `[${this.index}]`;
  }
}

/**
 * Represent a member access on a path to an erroneous value.
 *
 * @remarks
 *
 * Unlike a {@link PropertySegment}, which names a property of one of our
 * classes, a key names a member of an open JSON-able object. It is known only
 * at run time, and can be any string at all, so it is always rendered as
 * a subscript.
 */
export class KeySegment {
  /**
   * Object containing the value at {@link key}
   */
  readonly object: { readonly [key: string]: unknown };

  /**
   * Key of the value in the {@link object}
   */
  readonly key: string;

  constructor(object: { readonly [key: string]: unknown }, key: string) {
    this.object = object;
    this.key = key;
  }

  toString(): string {
    return `[${JSON.stringify(this.key)}]`;
  }
}

export type Segment = PropertySegment | IndexSegment | KeySegment;

/**
 * Represent the relative path to the erroneous value.
 */
export class Path {
  readonly segments: Array<Segment> = [];

  prepend(segment: Segment): void {
    this.segments.unshift(segment);
  }

  toString(): string {
    return this.segments.join("");
  }
}

/**
 * Represent a verification error in the data.
 */
export class VerificationError {
  // NOTE (mristin):
  // The name `VerificationError` is redundant since it lives in `verification` module,
  // and it would have made more sense to call it simply `Error`. Unfortunately in this case,
  // `Error` is a reserved name by JavaScript.

  /**
   * Human-readable description of the error
   */
  readonly message: string;

  /**
   * Path to the erroneous value
   */
  readonly path: Path = new Path();

  /**
   * Initialize with the given `message` and `path`.
   *
   * @remarks
   * If no `path` is specified, initialize with an empty path.
   */
  constructor(message: string, path: Path | null = null) {
    this.message = message;
    this.path = (path !== null)
      ? path
      : new Path();
  }
}

/**
 * Check the assignment to a property.
 */
export function setText(
  item: AasTypes.Item,
  text: string
): boolean {
  item.text = text;
  return true;
}

/**
 * Check the assignment of a value to an optional property.
 */
export function setMaybeText(
  item: AasTypes.Item,
  text: string
): boolean {
  item.maybeText = text;
  return true;
}

/**
 * Check the assignment of an optional value, and of an enumeration literal.
 */
export function copyMaybeTextAndSetMaybeKind(
  item: AasTypes.Item,
  other: AasTypes.Item
): boolean {
  item.maybeText = other.maybeText;
  item.maybeKind = AasTypes.Kind.Alpha;
  return true;
}

/**
 * Check the assignment to a property through a local alias of the object.
 */
export function setTextThroughAlias(
  item: AasTypes.Item,
  text: string
): boolean {
  const alias = item;
  alias.text = text;
  return true;
}

/**
 * Check the assignment of a list to a property.
 */
export function setTexts(
  item: AasTypes.Item,
  texts: Array<string>
): boolean {
  item.texts = texts;
  return true;
}

/**
 * Check the assignment to the items of a list, including a negative index.
 */
export function setFirstAndLastText(
  item: AasTypes.Item,
  text: string
): boolean {
  AasCommon.setAt(item.texts, 0, text);
  AasCommon.setAt(item.texts, -1, text);
  return true;
}

/**
 * Check the assignment to an item through a local alias of the list.
 */
export function setTextThroughListAlias(
  item: AasTypes.Item,
  text: string
): boolean {
  const texts = item.texts;
  AasCommon.setAt(texts, 1, text);
  return true;
}

/**
 * Check the assignment to the items of a list parameter.
 */
export function setNumbers(
  numbers: Array<number>,
  number: number
): boolean {
  AasCommon.setAt(numbers, 0, number);
  AasCommon.setAt(numbers, -2, AasCommon.at(numbers, -1) + 1);
  return true;
}

/**
 * Check the assignment to the items of a list nested in a list.
 */
export function setNestedText(
  items: Array<AasTypes.Item>,
  text: string
): boolean {
  AasCommon.setAt(AasCommon.at(items, 0).texts, -1, text);
  AasCommon.at(items, -1).text = text;
  return true;
}

/**
 * Check the assignment of an object to an item of a list.
 */
export function replaceFirstItem(
  items: Array<AasTypes.Item>,
  item: AasTypes.Item
): boolean {
  AasCommon.setAt(items, 0, item);
  return true;
}

/**
 * Check the assignment to the properties of the objects iterated over.
 */
export function setTextsInLoops(
  items: Array<AasTypes.Item>,
  text: string
): boolean {
  for (const item of items) {
    item.text = text;
  }
  for (let i = 0; i < items.length; i++) {
    AasCommon.setAt(AasCommon.at(items, i).texts, 0, text);
  }
  return true;
}

/**
 * Verify an instance of the model recursively or non-recursively (depending on the context).
 */
class Verifier
  extends AasTypes.AbstractTransformerWithContext<
    boolean, IterableIterator<VerificationError>
  > {
  *transformItemWithContext(
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    that: AasTypes.Item,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    context: boolean
  ): IterableIterator<VerificationError> {
    // No verification has been defined for Item.
  }

  *transformSomethingWithContext(
    that: AasTypes.Something,
    context: boolean
  ): IterableIterator<VerificationError> {
    if (context === true) {
      let itemsIndex = 0;
      for (const item of that.items) {
        for (const error of this.transformWithContext(item, context)) {
          error.path.prepend(
            new IndexSegment(
              that.items,
              itemsIndex
            )
          );
          error.path.prepend(
            new PropertySegment(
              that,
              "items"
            )
          );
          yield error;
        }
        itemsIndex++;
      }
    }
  }
}

const VERIFIER = new Verifier();

/**
 * Verify the constraints of `that`.
 *
 * @param that - instance to be verified
 * @param recurse - if set, continue the verification recursively
 * @returns a stream of verification errors
 */
export function *verify(
  that: AasTypes.Class,
  recurse = true
): IterableIterator<VerificationError> {
  yield * VERIFIER.transformWithContext(that, recurse);
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
