/**
 * Provide de/serialization of AAS classes to/from XML.
 *
 * The implementation is incremental and follows a SAX-style parsing approach.
 *
 * @remarks
 *
 * The primitives which every reader and writer of XML shares -- the cursor, the
 * checks of the namespace and the consumption of the tags -- live in
 * the `xmlcommon` module, and so do the error classes and the path, which this
 * module re-exports so that they stay where a caller has always found them.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasCommon from "./common";
import * as AasTypes from "./types";
import * as AasStringification from "./stringification";

import {
  ContentParser,
  DeserializationError,
  ElementSegment,
  SerializationError,
  XmlCursor,
  collapseWhitespace,
  consumeCloseTag,
  currentTokenKind,
  escapeXmlText,
  localNameOfTag,
  matchesXsBase64Binary,
  newDeserializationError,
  nextPropertyOpenTag,
  parseElementContent,
  parseList,
  parseNamedElement,
  parseTextContent,
  readRequiredRootOpenTag,
  removeWhitespace,
  tokenizeXml,
  writeElement,
  writeList,
  writeOptionalProperty,
  writeProperty
} from "./xmlcommon";

export {
  DeserializationError,
  ElementSegment,
  IndexSegment,
  KeySegment,
  Path,
  SerializationError
} from "./xmlcommon";
export type { Segment } from "./xmlcommon";

/**
 * Parse the content of an XML element as a literal of the enumeration called
 * `enumerationName`, looking the text up with `fromString`.
 *
 * The lookup lives in the stringification module already, so this function is
 * generic over it, and every enumeration of the meta-model shares it. The name
 * of the enumeration is the only thing it adds, for the error message.
 *
 * @param cursor - to read from
 * @param enumerationName - name of the enumeration, for the error message
 * @param fromString - gives the literal for the text, or `null`
 * @returns parsed literal, or an error
 * @typeParam T - type of the enumeration
 */
function parseEnumerationContent<T>(
  cursor: XmlCursor,
  enumerationName: string,
  fromString: (text: string) => T | null
): AasCommon.Either<T, DeserializationError> {
  const text = parseTextContent(cursor);

  const literal = fromString(text);
  if (literal === null) {
    return newDeserializationError<T>(
      `Unexpected literal of ${enumerationName}: ${text}`
    );
  }

  return new AasCommon.Either<T, DeserializationError>(literal, null);
}

/**
 * Report that the property `localName` occurred more than once.
 *
 * The check itself sits in the property loop, right in front of the parse, since
 * only the loop knows whether the property's variable has been set already. This
 * is only the error, so that the message is written once instead of at every one
 * of the property cases.
 */
function duplicatePropertyError(localName: string): DeserializationError {
  return new DeserializationError(
    "Property " + localName + " occurred more than once"
  );
}

function parse_bool(
  cursor: XmlCursor
): AasCommon.Either<boolean, DeserializationError> {
  const text = collapseWhitespace(parseTextContent(cursor));

  if (text === "true" || text === "1") {
    return new AasCommon.Either<boolean, DeserializationError>(true, null);
  }
  if (text === "false" || text === "0") {
    return new AasCommon.Either<boolean, DeserializationError>(false, null);
  }

  return newDeserializationError<boolean>(
    `Expected xs:boolean text, but got: ${text}`
  );
}

function parse_int(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = collapseWhitespace(parseTextContent(cursor));

  if (!/^[+-]?\d+$/.test(text)) {
    return newDeserializationError<number>(
      `Expected integer text, but got: ${text}`
    );
  }

  const value = Number(text);

  // NOTE (mristin):
  // An integer is a ``number`` in TypeScript, and a ``number`` holds only
  // the integers up to 2^53 - 1 exactly. Beyond that ``Number`` rounds
  // silently -- 9007199254740993 comes back as 9007199254740992, and
  // 9223372036854775807 as 9223372036854776000, which is a perfectly
  // well-formed but *different* xs:long. We refuse instead of corrupting.
  //
  // ``Number.isSafeInteger`` covers ``Number.isInteger`` as well, so
  // a non-integer is refused here too.
  if (!Number.isSafeInteger(value)) {
    return newDeserializationError<number>(
      `Expected an integer within the safe range of a number, `
        + `but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parse_float(
  cursor: XmlCursor
): AasCommon.Either<number, DeserializationError> {
  const text = collapseWhitespace(parseTextContent(cursor));

  // NOTE (mristin):
  // `+INF` is read although it is written as `INF`: XSD 1.1 admits it, its
  // production being `(\+|-)?INF`, and being liberal in what we accept
  // costs nothing here.
  if (text === "INF" || text === "+INF") {
    return new AasCommon.Either<number, DeserializationError>(Infinity, null);
  }
  if (text === "-INF") {
    return new AasCommon.Either<number, DeserializationError>(-Infinity, null);
  }
  if (text === "NaN") {
    return new AasCommon.Either<number, DeserializationError>(NaN, null);
  }

  // NOTE (mristin):
  // ``Number`` is far too permissive to be trusted with the text: it reads
  // an empty string and a run of whitespace as 0, a hexadecimal, binary or
  // octal prefix as the number it spells -- ``0x10`` as 16 -- and
  // ``Infinity`` as an infinity, none of which is a valid ``xs:double``.
  //
  // See: https://www.w3.org/TR/xmlschema-2/#double
  if (!/^(\+|-)?([0-9]+(\.[0-9]*)?|\.[0-9]+)([Ee](\+|-)?[0-9]+)?$/.test(text)) {
    return newDeserializationError<number>(
      `Expected xs:double text, but got: ${text}`
    );
  }

  const value = Number(text);
  if (Number.isNaN(value)) {
    return newDeserializationError<number>(
      `Expected xs:double text, but got: ${text}`
    );
  }

  return new AasCommon.Either<number, DeserializationError>(value, null);
}

function parse_str(
  cursor: XmlCursor
): AasCommon.Either<string, DeserializationError> {
  return new AasCommon.Either<string, DeserializationError>(
    parseTextContent(cursor),
    null
  );
}

function parse_bytes(
  cursor: XmlCursor
): AasCommon.Either<Uint8Array, DeserializationError> {
  // NOTE (mristin):
  // ``xs:base64Binary`` allows whitespace between the characters, and not
  // only around them, while the decoder accepts none of it. So every
  // whitespace character is dropped, and not merely collapsed.
  //
  // See: https://www.w3.org/TR/xmlschema-2/#base64Binary
  const text = removeWhitespace(parseTextContent(cursor));

  if (!matchesXsBase64Binary(text)) {
    return newDeserializationError<Uint8Array>(
      `Expected a text as base64-encoded bytes, but got: ${text}`
    );
  }

  const decodedOrError = AasCommon.base64Decode(text);
  if (decodedOrError.error !== null) {
    return newDeserializationError<Uint8Array>(
      decodedOrError.error
    );
  }

  return new AasCommon.Either<Uint8Array, DeserializationError>(
    decodedOrError.mustValue(),
    null
  );
}

function parse_Kind(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Kind, DeserializationError> {
  return parseEnumerationContent(
    cursor,
    "Kind",
    AasStringification.kindFromString
  );
}

function write_Kind(
  parts: Array<string>,
  value: AasTypes.Kind
): void {
  writeEnumerationContent(
    parts,
    value,
    "Kind",
    AasStringification.kindToString
  );
}

function parseAtV_str(
  cursor: XmlCursor
): AasCommon.Either<string, DeserializationError> {
  return parseNamedElement(
    cursor,
    "v",
    parse_str
  );
}

function parseElement_Item(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Item, DeserializationError> {
  return parseNamedElement(
    cursor,
    "item",
    parseItemFromSequence
  );
}

function parse_ListOf_Item(
  cursor: XmlCursor
): AasCommon.Either<Array<AasTypes.Item>, DeserializationError> {
  return parseList<AasTypes.Item>(
    cursor,
    parseElement_Item
  );
}

function parse_ListOf_str(
  cursor: XmlCursor
): AasCommon.Either<Array<string>, DeserializationError> {
  return parseList<string>(
    cursor,
    parseAtV_str
  );
}

function writeAtV_str(
  parts: Array<string>,
  value: string
): void {
  writeElement(
    parts,
    "v",
    value,
    write_str
  );
}

function write_ListOf_str(
  parts: Array<string>,
  values: Array<string>
): void {
  writeList(
    parts,
    values,
    writeAtV_str
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Item}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Item} is embedded.
 */
function parseItemFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Item, DeserializationError> {
  let theText: string | null = null;
  let theMaybeText: string | null = null;
  let theMaybeKind: AasTypes.Kind | null = null;
  let theTexts: Array<string> | null = null;

  const className = AasTypes.Item.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Item, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "text": {
        if (theText !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parse_str
        );
        propertyError = parsed.error;
        theText = parsed.value;
        break;
      }

      case "maybeText": {
        if (theMaybeText !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parse_str
        );
        propertyError = parsed.error;
        theMaybeText = parsed.value;
        break;
      }

      case "maybeKind": {
        if (theMaybeKind !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parse_Kind
        );
        propertyError = parsed.error;
        theMaybeKind = parsed.value;
        break;
      }

      case "texts": {
        if (theTexts !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parse_ListOf_str
        );
        propertyError = parsed.error;
        theTexts = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new ElementSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Item, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theText === null) {
    return newDeserializationError<AasTypes.Item>(
      "The required property 'text' is missing"
    );
  }

  if (theTexts === null) {
    return newDeserializationError<AasTypes.Item>(
      "The required property 'texts' is missing"
    );
  }

  const instance = new AasTypes.Item(
    theText,
    theTexts,
    theMaybeText,
    theMaybeKind
  );
  return new AasCommon.Either<AasTypes.Item, DeserializationError>(
    instance,
    null
  );
}

/**
 * Parse the sequence of properties of an instance
 * of {@link types!Something}.
 *
 * The opening tag is expected to have been already read by the caller, and
 * the caller is expected to read and verify the corresponding closing tag
 * after this function returns successfully. This is the contract of
 * a `ContentParser`, so this function is used as one wherever an instance
 * of {@link types!Something} is embedded.
 */
function parseSomethingFromSequence(
  cursor: XmlCursor
): AasCommon.Either<AasTypes.Something, DeserializationError> {
  let theItems: Array<AasTypes.Item> | null = null;

  const className = AasTypes.Something.name;

  cursor.skipIgnorable();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const nextTagOrError = nextPropertyOpenTag(cursor, className);
    if (nextTagOrError === null) {
      break;
    }
    if (nextTagOrError instanceof DeserializationError) {
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        nextTagOrError
      );
    }

    const propertyLocalName = localNameOfTag(nextTagOrError.tag);

    let propertyError: DeserializationError | null = null;
    switch (propertyLocalName) {
      case "items": {
        if (theItems !== null) {
          propertyError = duplicatePropertyError(propertyLocalName);
          break;
        }

        const parsed = parseElementContent(
          cursor,
          propertyLocalName,
          parse_ListOf_Item
        );
        propertyError = parsed.error;
        theItems = parsed.value;
        break;
      }

      default: {
        propertyError = new DeserializationError(
          `Unexpected XML property: ${propertyLocalName}`
        );
        break;
      }
    }

    if (propertyError !== null) {
      propertyError.path.prepend(new ElementSegment(propertyLocalName));
      return new AasCommon.Either<AasTypes.Something, DeserializationError>(
        null,
        propertyError
      );
    }

    cursor.skipIgnorable();
  }

  if (theItems === null) {
    return newDeserializationError<AasTypes.Something>(
      "The required property 'items' is missing"
    );
  }

  const instance = new AasTypes.Something(
    theItems
  );
  return new AasCommon.Either<AasTypes.Something, DeserializationError>(
    instance,
    null
  );
}

/**
 * Write the properties of an instance
 * of {@link types!Item}, and neither the opening
 * nor the closing tag of the element which holds them -- which is the contract of
 * a `ContentWriter`, so this function is used as one.
 */
function writeItemAsSequence(
  parts: Array<string>,
  that: AasTypes.Item
): void {
  writeProperty(
    parts,
    "text",
    that.text,
    write_str
  );
  writeOptionalProperty(
    parts,
    "maybeText",
    that.maybeText,
    write_str
  );
  writeOptionalProperty(
    parts,
    "maybeKind",
    that.maybeKind,
    write_Kind
  );
  writeProperty(
    parts,
    "texts",
    that.texts,
    write_ListOf_str
  );
}

/**
 * Write the properties of an instance
 * of {@link types!Something}, and neither the opening
 * nor the closing tag of the element which holds them -- which is the contract of
 * a `ContentWriter`, so this function is used as one.
 */
function writeSomethingAsSequence(
  parts: Array<string>,
  that: AasTypes.Something
): void {
  writeProperty(
    parts,
    "items",
    that.items,
    writeListOfInstances
  );
}

const ROOT_DISPATCH_BY_LOCAL_NAME = new Map<
  string,
  ContentParser<AasTypes.Class>
>([
  ["item", parseItemFromSequence],
  ["something", parseSomethingFromSequence]
]);

/**
 * Parse an XML string as an AAS instance.
 *
 * @param xml - XML string to parse
 * @returns parsed AAS instance or an error
 */
export function fromXmlString(
  xml: string
): AasCommon.Either<AasTypes.Class, DeserializationError> {
  if (xml.length === 0) {
    return newDeserializationError<AasTypes.Class>(
      "Expected an XML document, but got an empty string"
    );
  }

  const tokensOrError = tokenizeXml(xml);
  if (tokensOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      tokensOrError.error
    );
  }

  const cursor = new XmlCursor(tokensOrError.mustValue());

  const rootOpenTagOrError = readRequiredRootOpenTag(cursor);
  if (rootOpenTagOrError.error !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      rootOpenTagOrError.error
    );
  }

  const rootOpenTag = rootOpenTagOrError.mustValue();
  const rootLocalName = localNameOfTag(rootOpenTag.tag);

  const dispatch = ROOT_DISPATCH_BY_LOCAL_NAME.get(rootLocalName);
  if (dispatch === undefined) {
    return newDeserializationError<AasTypes.Class>(
      `Unexpected root XML element: ${rootLocalName}`
    );
  }

  const instanceOrError = dispatch(cursor);
  if (instanceOrError.error !== null) {
    return instanceOrError;
  }

  const closeError = consumeCloseTag(cursor, rootLocalName);
  if (closeError !== null) {
    return new AasCommon.Either<AasTypes.Class, DeserializationError>(
      null,
      closeError
    );
  }

  cursor.skipIgnorable();
  if (cursor.current() !== null) {
    return newDeserializationError<AasTypes.Class>(
      "Expected no tokens after the root XML element, but got token kind: " +
        currentTokenKind(cursor)
    );
  }

  return instanceOrError;
}

/**
 * Write the instances of `values`, each as its own, self-describing XML element.
 *
 * @remarks
 *
 * Every item goes through {@link writeClass} whatever its declared type is, so
 * this one writer serves every list of instances in the meta-model.
 */
function writeListOfInstances(
  parts: Array<string>,
  values: Array<AasTypes.Class>
): void {
  writeList(parts, values, writeClass);
}

/**
 * Write `that` as its own, self-describing XML element.
 *
 * @remarks
 *
 * Which element that is, is decided by the run-time type of `that`, so this one
 * writer serves every abstract class, every named union, and the item of a list
 * or of a tuple of any class at all. The reading, which has to decide what to
 * construct before it has read anything, needs a dispatcher per interface instead.
 */
function writeClass(parts: Array<string>, that: AasTypes.Class): void {
  SERIALIZER.visitWithContext(that, parts);
}

/**
 * Write the literal `value` of the enumeration `enumerationName` as the content
 * of an XML element.
 *
 * @remarks
 *
 * We deliberately go through the `toString` of the stringification module, which
 * gives out `null` for a literal it does not know, and not through its `mustToString`,
 * which throws an error of its own. An instance carrying a literal outside its
 * enumeration is exactly the kind of failure this module reports with a path.
 */
function writeEnumerationContent<T>(
  parts: Array<string>,
  value: T,
  enumerationName: string,
  toString: (value: T) => string | null
): void {
  const text = toString(value);
  if (text === null) {
    throw new SerializationError(
      `Invalid literal of ${enumerationName}: ${value}`
    );
  }

  parts.push(escapeXmlText(text));
}

function write_bool(
  parts: Array<string>,
  value: boolean
): void {
  parts.push(value ? "true" : "false");
}

function write_int(
  parts: Array<string>,
  value: number
): void {
  // NOTE (mristin):
  // Beyond 2^53 - 1 a ``number`` no longer holds every integer, so the value
  // we were handed has already lost its identity -- writing it out would
  // record a different xs:long without a word. ``Number.isSafeInteger``
  // covers ``Number.isInteger`` as well.
  if (!Number.isSafeInteger(value)) {
    throw new SerializationError(
      `Expected an integer within the safe range of a number, `
        + `but got: ${value}`
    );
  }

  parts.push(`${value}`);
}

function write_float(
  parts: Array<string>,
  value: number
): void {
  if (Number.isNaN(value)) {
    parts.push("NaN");
  } else if (value === Infinity) {
    parts.push("INF");
  } else if (value === -Infinity) {
    parts.push("-INF");
  } else if (Object.is(value, -0)) {
    // NOTE (mristin):
    // ``${-0}`` is "0", so the sign would be dropped, and a negative zero
    // would come back as a positive one. ``-0`` is a valid xs:double, and
    // the other SDKs keep the sign, so we keep it too. Mind that
    // ``value === -0`` is true for a positive zero as well, which is why
    // this asks ``Object.is``.
    parts.push("-0");
  } else {
    parts.push(`${value}`);
  }
}

function write_str(
  parts: Array<string>,
  value: string
): void {
  parts.push(escapeXmlText(value));
}

function write_bytes(
  parts: Array<string>,
  value: Uint8Array
): void {
  parts.push(escapeXmlText(AasCommon.base64Encode(value)));
}

/**
 * Write the XML element of an instance, dispatching on its run-time type.
 *
 * Each method writes the whole element -- the tags included -- since the element
 * is picked by the run-time type, which this dispatch has just established. The
 * properties are written by the corresponding module-level `write{Cls}AsSequence`,
 * which is the content writer of that very element.
 */
class Serializer extends AasTypes.AbstractVisitorWithContext<Array<string>> {
  visitItemWithContext(
    that: AasTypes.Item,
    parts: Array<string>
  ): void {
    writeElement(
      parts,
      "item",
      that,
      writeItemAsSequence
    );
  }

  visitSomethingWithContext(
    that: AasTypes.Something,
    parts: Array<string>
  ): void {
    writeElement(
      parts,
      "something",
      that,
      writeSomethingAsSequence
    );
  }
}

const SERIALIZER = new Serializer();

/**
 * Serialize an AAS instance as an XML string.
 *
 * @param that - AAS instance to serialize
 * @returns serialized XML string
 * @throws {@link SerializationError} if `that` can not be serialized, *e.g.*, if
 * a property expected to be an integer holds a fractional number
 */
export function toXmlString(that: AasTypes.Class): string {
  const parts = new Array<string>();
  writeClass(parts, that);
  return parts.join("");
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
