"""
Verify that the instances of the meta-model satisfy the invariants.

Here is an example how to verify an instance of :py:class:`dummy.types.ChildA`:

.. code-block::

    import dummy.types as our_types
    import dummy.verification as our_verification

    an_instance = our_types.ChildA(
        # ... some constructor arguments ...
    )

    for error in our_verification.verify(an_instance):
        print(f"{error.cause} at: {error.path}")
"""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


import collections.abc
import math
import re
import struct
import sys
from typing import (
    Any,
    Callable,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Pattern,
    Sequence,
    Set,
    Tuple,
    Union
)

if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final

from dummy import (
    constants as our_constants,
    reporting as our_reporting,
    types as our_types,
)


PropertySegment = our_reporting.PropertySegment
IndexSegment = our_reporting.IndexSegment
KeySegment = our_reporting.KeySegment
Segment = our_reporting.Segment
Path = our_reporting.Path

Error = our_reporting.Error


def absolute_is_small(
    number: int
) -> bool:
    """Check the assertion without a message."""
    # pylint: disable=all
    absolute = number
    if number < 0:
        absolute = -number
    assert absolute >= 0
    return absolute < 1000


def optional_text_is_short(
    text: Optional[str]
) -> bool:
    """Check the narrowing of an optional argument by an assertion."""
    # pylint: disable=all
    assert text is not None, 'The caller must check the text for "None" — always'
    return len(text) < 10


def child_a_is_small(
    parent: our_types.Parent
) -> bool:
    """Check the narrowing of an argument to a class by an assertion."""
    # pylint: disable=all
    assert isinstance(parent, our_types.ChildA), 'The caller must check for Child_a'
    return parent.a_only < 100


def few_matches(
    texts: Sequence[str],
    text: str
) -> bool:
    """
    Check the assertion with an f-string as the message in a for-loop.
    """
    # pylint: disable=all
    count = 0
    for other in texts:
        if other == text:
            count = count + 1
        assert count <= len(texts), f'Expected at most {len(texts)} matches, but got {count}'
    return count < 3


def texts_are_consistent(
    texts: Sequence[str],
    text: str,
    number: int
) -> bool:
    """
    Check the condition which the targets break over multiple lines.
    """
    # pylint: disable=all
    if (
        (
            len(texts) >= 5
            and len(text) == 0
        )
    ):
        return False
    assert (
        (
            len(texts) < 5
            or len(text) > 0
            or number < -1000
        )
    ), 'The early return rules out many texts with an empty text'
    return True


class _Transformer(
        our_types.AbstractTransformer[
            Iterator[Error]
        ]
):
    # noinspection PyMethodMayBeStatic
    def transform_child_a(
            self,
            that: our_types.ChildA
    ) -> Iterator[Error]:
        # No verification has been defined for ChildA.
        return
        # For this uncommon return-yield construction, see:
        # https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
        # noinspection PyUnreachableCode
        yield

    # noinspection PyMethodMayBeStatic
    def transform_child_b(
            self,
            that: our_types.ChildB
    ) -> Iterator[Error]:
        # No verification has been defined for ChildB.
        return
        # For this uncommon return-yield construction, see:
        # https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
        # noinspection PyUnreachableCode
        yield

    # noinspection PyMethodMayBeStatic
    def transform_something(
            self,
            that: our_types.Something
    ) -> Iterator[Error]:
        if not (that.doubled_number() != 666):
            yield Error(
                'Doubled number must not be devilish'
            )

        if not (
            texts_are_consistent(
                that.texts,
                that.text,
                that.number
            )
        ):
            yield Error(
                'Many texts require a non-empty text'
            )

        if not few_matches(that.texts, that.text):
            yield Error(
                'Text must appear at most twice in the texts'
            )

        if not (
            not isinstance(that.parent, our_types.ChildA)
            or child_a_is_small(that.parent)
        ):
            yield Error(
                'Parent as Child_a must have a small a_only'
            )

        if not (
            not (that.optional_text is not None)
            or optional_text_is_short(that.optional_text)
        ):
            yield Error(
                'Optional text must be short'
            )

        if not absolute_is_small(that.number):
            yield Error(
                'Number must be between minus one thousand and one thousand'
            )

        for error in verify(that.parent):
            error.path._prepend(
                PropertySegment(
                    that,
                    'parent'
                )
            )
            yield error


_TRANSFORMER = _Transformer()


def verify(
        that: our_types.Class
) -> Iterator[Error]:
    """
    Verify the constraints of :paramref:`that` recursively.

    :param that: instance whose constraints we want to verify
    :yield: constraint violations
    """
    yield from _TRANSFORMER.transform(that)


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
