/**
 * Test `modelType()` methods.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasTypes from "../src/types";
import * as AasStringification from "../src/stringification";
import * as TestCommonJsonization from "./commonJsonization";

test("model type of SomeItem", () => {
  const instance = TestCommonJsonization.loadMinimalSomeItem();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.SomeItem
  );
});

test("model type from string of SomeItem", () => {
  const text = "SomeItem";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.SomeItem
  );
});

test("model type to string of SomeItem", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.SomeItem
  );

  expect(text).toStrictEqual(
    "SomeItem"
  );
});

test("model type of AnotherItem", () => {
  const instance = TestCommonJsonization.loadMinimalAnotherItem();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.AnotherItem
  );
});

test("model type from string of AnotherItem", () => {
  const text = "AnotherItem";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.AnotherItem
  );
});

test("model type to string of AnotherItem", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.AnotherItem
  );

  expect(text).toStrictEqual(
    "AnotherItem"
  );
});

test("model type of Simple", () => {
  const instance = TestCommonJsonization.loadMinimalSimple();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.Simple
  );
});

test("model type from string of Simple", () => {
  const text = "Simple";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.Simple
  );
});

test("model type to string of Simple", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.Simple
  );

  expect(text).toStrictEqual(
    "Simple"
  );
});

test("model type of Something", () => {
  const instance = TestCommonJsonization.loadMinimalSomething();

  expect(instance.modelType()).toStrictEqual(
    AasTypes.ModelType.Something
  );
});

test("model type from string of Something", () => {
  const text = "Something";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toStrictEqual(
    AasTypes.ModelType.Something
  );
});

test("model type to string of Something", () => {
  const text = AasStringification.mustModelTypeToString(
    AasTypes.ModelType.Something
  );

  expect(text).toStrictEqual(
    "Something"
  );
});

test("model type from invalid string", () => {
  const text = "This is definitely not a valid model type.";
  const literal = AasStringification.modelTypeFromString(
    text
  );

  expect(literal).toBeNull();
});

test("invalid model type to string", () => {
  // The number 9007199254740991 is the maximum safe integer.
  const literal = <AasTypes.ModelType>9007199254740991;
  const text = AasStringification.modelTypeToString(
    literal
  );

  expect(text).toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
