// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_examples.hpp"
#include "./common_xmlization.hpp"

#include <dummy/iteration.hpp>
#include <dummy/stringification.hpp>

#include <filesystem>

namespace aas = dummy;

namespace test {
namespace common {
namespace examples {

template<typename T>
struct StaticTypeName;

template<>
struct StaticTypeName<
  aas::types::ISomeItem
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::ISomeItem
>::name = "ISomeItem";

template<>
struct StaticTypeName<
  aas::types::IAnotherItem
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::IAnotherItem
>::name = "IAnotherItem";

template<>
struct StaticTypeName<
  aas::types::ISomething
> {
  static const char* name;
};
const char* StaticTypeName<
  aas::types::ISomething
>::name = "ISomething";

std::shared_ptr<
  aas::types::ISomeItem
> LoadSomeItem(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::ISomeItem
  > instance(
    std::dynamic_pointer_cast<
      aas::types::ISomeItem
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to ISomeItem from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::ISomeItem
> LoadMinSomeItem() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "someItem"
      / "minimal.xml"
  );

  return LoadSomeItem(
    path
  );
}

std::shared_ptr<
  aas::types::ISomeItem
> LoadMaxSomeItem() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "someItem"
      / "maximal.xml"
  );

  return LoadSomeItem(
    path
  );
}

std::shared_ptr<
  aas::types::IAnotherItem
> LoadAnotherItem(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::IAnotherItem
  > instance(
    std::dynamic_pointer_cast<
      aas::types::IAnotherItem
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to IAnotherItem from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::IAnotherItem
> LoadMinAnotherItem() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "anotherItem"
      / "minimal.xml"
  );

  return LoadAnotherItem(
    path
  );
}

std::shared_ptr<
  aas::types::IAnotherItem
> LoadMaxAnotherItem() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "anotherItem"
      / "maximal.xml"
  );

  return LoadAnotherItem(
    path
  );
}

std::shared_ptr<
  aas::types::ISomething
> LoadSomething(
  const std::filesystem::path& path
) {
  

  std::shared_ptr<
    aas::types::IClass
  > abstract = test::common::xmlization::MustReadInstance(
    path
  );

  std::shared_ptr<
    aas::types::ISomething
  > instance(
    std::dynamic_pointer_cast<
      aas::types::ISomething
    >(
      abstract
    )
  );

  if (instance == nullptr) {
    throw std::runtime_error(
      aas::common::Concat(
        "Failed to cast the instance to ISomething from ",
        path.string()
      )
    );
  }

  return instance;
}

std::shared_ptr<
  aas::types::ISomething
> LoadMinSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "minimal.xml"
  );

  return LoadSomething(
    path
  );
}

std::shared_ptr<
  aas::types::ISomething
> LoadMaxSomething() {
  const std::filesystem::path path(
    test::common::DetermineTestDataDir()
      / "Xml"
      / "Expected"
      / "something"
      / "maximal.xml"
  );

  return LoadSomething(
    path
  );
}

}  // namespace examples
}  // namespace common
}  // namespace test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
