// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

#include "./common.hpp"
#include "./common_jsonization.hpp"

#include <dummy/jsonization.hpp>

#include <limits>

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

namespace our = dummy;

template<class ClassT>
void AssertRoundTrip(
  const std::filesystem::path& path,
  std::function<
    our::common::expected<
      std::shared_ptr<ClassT>,
      our::jsonization::DeserializationError
    >(const nlohmann::json&, bool)
  > deserialization_function
) {
  const nlohmann::json json = test::common::jsonization::MustReadJson(path);

  our::common::expected<
    std::shared_ptr<ClassT>,
    our::jsonization::DeserializationError
  > deserialized = deserialization_function(json, false);

  if (!deserialized.has_value()) {
    INFO(
      our::common::Concat(
        "Failed to de-serialize from ",
        path.string(),
        ": ",
        our::common::WstringToUtf8(
          deserialized.error().path.ToWstring()
        ),
        ": ",
        our::common::WstringToUtf8(
          deserialized.error().cause
        )
      )
    )
    REQUIRE(deserialized.has_value());
  }

  nlohmann::json another_json = our::jsonization::Serialize(
    *(deserialized.value())
  );

  std::optional<std::string> diff_message = test::common::jsonization::CompareJsons(
    json,
    another_json
  );
  if (diff_message.has_value()) {
    INFO(
      our::common::Concat(
        "The JSON round-trip from ",
        path.string(),
        " failed. There is a diff between the original JSON "
        "and the serialized one: ",
        *diff_message
      )
    )
    REQUIRE(!diff_message.has_value());
  }
}

template<typename ClassT>
void AssertDeserializationFailure(
  const std::filesystem::path& path,
  std::function<
    our::common::expected<
      std::shared_ptr<ClassT>,
      our::jsonization::DeserializationError
    >(const nlohmann::json&, bool)
  > deserialization_function,
  const std::filesystem::path& error_path
) {
  const nlohmann::json json = test::common::jsonization::MustReadJson(path);

  our::common::expected<
    std::shared_ptr<ClassT>,
    our::jsonization::DeserializationError
  > deserialized = deserialization_function(json, false);

  if (deserialized.has_value()) {
    INFO(
      our::common::Concat(
        "Expected the de-serialization to fail on ",
        path.string(),
        ", but the de-serialization succeeded"
      )
    )
    REQUIRE(!deserialized.has_value());
  }

  test::common::AssertContentEqualsExpectedOrRecord(
    our::common::Concat(
      our::common::WstringToUtf8(
        deserialized.error().path.ToWstring()
      ),
      ": ",
      our::common::WstringToUtf8(
        deserialized.error().cause
      )
    ),
    error_path
  );
}

const std::filesystem::path& DetermineJsonDir() {
  static our::common::optional<std::filesystem::path> result;
  if (!result.has_value()) {
    result = test::common::DetermineTestDataDir() / "Json";
  }

  return *result;
}

const std::filesystem::path& DetermineErrorDir() {
  static our::common::optional<std::filesystem::path> result;
  if (!result.has_value()) {
    result = test::common::DetermineTestDataDir() / "JsonizationError";
  }

  return *result;
}

template<class ClassT>
std::shared_ptr<ClassT> MustDeserializeTheFirstExpected(
  const std::string& model_type,
  std::function<
    our::common::expected<
      std::shared_ptr<ClassT>,
      our::jsonization::DeserializationError
    >(const nlohmann::json&, bool)
  > deserialization_function
) {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir() / "Expected" / model_type,
      ".json"
    )
  );

  INFO("We expect at least one recorded example of " + model_type)
  REQUIRE(!paths.empty());

  const nlohmann::json json = test::common::jsonization::MustReadJson(
    paths.front()
  );

  our::common::expected<
    std::shared_ptr<ClassT>,
    our::jsonization::DeserializationError
  > deserialized = deserialization_function(json, false);

  INFO(
    our::common::Concat(
      "Failed to de-serialize from ",
      paths.front().string()
    )
  )
  REQUIRE(deserialized.has_value());

  return deserialized.value();
}

/**
 * Assert that \p that instance can not be serialized to JSON, and that
 * the failure is reported at \p expected_path.
 */
void AssertSerializationFailsAt(
  const our::types::IClass& that,
  const std::string& expected_path
) {
  try {
    our::jsonization::Serialize(that);
  } catch (const our::jsonization::SerializationException& exception) {
    const std::string observed_path(
      our::common::WstringToUtf8(
        exception.path().ToWstring()
      )
    );

    INFO(
      our::common::Concat(
        "Expected the serialization to fail at ",
        expected_path,
        ", but it failed at ",
        observed_path,
        ": ",
        our::common::WstringToUtf8(exception.cause())
      )
    )
    REQUIRE(observed_path == expected_path);

    return;
  }

  INFO(
    our::common::Concat(
      "Expected the serialization to fail at ",
      expected_path,
      ", but it succeeded"
    )
  )
  REQUIRE(false);
}

TEST_CASE("Test the round-trip of an expected AbstractDescendantWithoutNumbers") {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir()
        / "Expected"
        / "AbstractDescendantWithoutNumbers",
      ".json"
    )
  );

  for (const std::filesystem::path& path : paths) {
    AssertRoundTrip<
      our::types::IAbstractDescendantWithoutNumbers
    >(path, our::jsonization::AbstractDescendantWithoutNumbersFrom);
  }
}

TEST_CASE("Test the de-serialization failure on an unexpected AbstractDescendantWithoutNumbers") {
  for (
    const std::filesystem::path& causeDir
    : test::common::ListSubdirectories(
      DetermineJsonDir()
        / "Unexpected"
        / "Unserializable"
    )
  ) {
    for (
      const std::filesystem::path& path
      : test::common::FindFilesBySuffixRecursively(
        causeDir / "AbstractDescendantWithoutNumbers",
        ".json"
      )
    ) {
      const std::filesystem::path parent(
        (
          DetermineErrorDir()
          / std::filesystem::relative(path, DetermineJsonDir())
        ).parent_path()
      );

      const std::filesystem::path error_path(
        parent
        / (path.filename().string() + ".error")
      );

      AssertDeserializationFailure<
        our::types::IAbstractDescendantWithoutNumbers
      >(
        path,
        our::jsonization::AbstractDescendantWithoutNumbersFrom,
        error_path
      );
    }
  }
}

TEST_CASE("Test the round-trip of an expected ParentWithoutNumbers") {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir()
        / "Expected"
        / "ParentWithoutNumbers",
      ".json"
    )
  );

  for (const std::filesystem::path& path : paths) {
    AssertRoundTrip<
      our::types::IParentWithoutNumbers
    >(path, our::jsonization::ParentWithoutNumbersFrom);
  }
}

TEST_CASE("Test the de-serialization failure on an unexpected ParentWithoutNumbers") {
  for (
    const std::filesystem::path& causeDir
    : test::common::ListSubdirectories(
      DetermineJsonDir()
        / "Unexpected"
        / "Unserializable"
    )
  ) {
    for (
      const std::filesystem::path& path
      : test::common::FindFilesBySuffixRecursively(
        causeDir / "ParentWithoutNumbers",
        ".json"
      )
    ) {
      const std::filesystem::path parent(
        (
          DetermineErrorDir()
          / std::filesystem::relative(path, DetermineJsonDir())
        ).parent_path()
      );

      const std::filesystem::path error_path(
        parent
        / (path.filename().string() + ".error")
      );

      AssertDeserializationFailure<
        our::types::IParentWithoutNumbers
      >(
        path,
        our::jsonization::ParentWithoutNumbersFrom,
        error_path
      );
    }
  }
}

TEST_CASE("Test the round-trip of an expected ChildWithoutNumbers") {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir()
        / "Expected"
        / "ChildWithoutNumbers",
      ".json"
    )
  );

  for (const std::filesystem::path& path : paths) {
    AssertRoundTrip<
      our::types::IChildWithoutNumbers
    >(path, our::jsonization::ChildWithoutNumbersFrom);
  }
}

TEST_CASE("Test the de-serialization failure on an unexpected ChildWithoutNumbers") {
  for (
    const std::filesystem::path& causeDir
    : test::common::ListSubdirectories(
      DetermineJsonDir()
        / "Unexpected"
        / "Unserializable"
    )
  ) {
    for (
      const std::filesystem::path& path
      : test::common::FindFilesBySuffixRecursively(
        causeDir / "ChildWithoutNumbers",
        ".json"
      )
    ) {
      const std::filesystem::path parent(
        (
          DetermineErrorDir()
          / std::filesystem::relative(path, DetermineJsonDir())
        ).parent_path()
      );

      const std::filesystem::path error_path(
        parent
        / (path.filename().string() + ".error")
      );

      AssertDeserializationFailure<
        our::types::IChildWithoutNumbers
      >(
        path,
        our::jsonization::ChildWithoutNumbersFrom,
        error_path
      );
    }
  }
}

TEST_CASE("Test the round-trip of an expected WithNumber") {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir()
        / "Expected"
        / "WithNumber",
      ".json"
    )
  );

  for (const std::filesystem::path& path : paths) {
    AssertRoundTrip<
      our::types::IWithNumber
    >(path, our::jsonization::WithNumberFrom);
  }
}

TEST_CASE("Test the de-serialization failure on an unexpected WithNumber") {
  for (
    const std::filesystem::path& causeDir
    : test::common::ListSubdirectories(
      DetermineJsonDir()
        / "Unexpected"
        / "Unserializable"
    )
  ) {
    for (
      const std::filesystem::path& path
      : test::common::FindFilesBySuffixRecursively(
        causeDir / "WithNumber",
        ".json"
      )
    ) {
      const std::filesystem::path parent(
        (
          DetermineErrorDir()
          / std::filesystem::relative(path, DetermineJsonDir())
        ).parent_path()
      );

      const std::filesystem::path error_path(
        parent
        / (path.filename().string() + ".error")
      );

      AssertDeserializationFailure<
        our::types::IWithNumber
      >(
        path,
        our::jsonization::WithNumberFrom,
        error_path
      );
    }
  }
}

TEST_CASE("Test the round-trip of an expected Something") {
  const std::deque<std::filesystem::path> paths(
    test::common::FindFilesBySuffixRecursively(
      DetermineJsonDir()
        / "Expected"
        / "Something",
      ".json"
    )
  );

  for (const std::filesystem::path& path : paths) {
    AssertRoundTrip<
      our::types::ISomething
    >(path, our::jsonization::SomethingFrom);
  }
}

TEST_CASE("Test the de-serialization failure on an unexpected Something") {
  for (
    const std::filesystem::path& causeDir
    : test::common::ListSubdirectories(
      DetermineJsonDir()
        / "Unexpected"
        / "Unserializable"
    )
  ) {
    for (
      const std::filesystem::path& path
      : test::common::FindFilesBySuffixRecursively(
        causeDir / "Something",
        ".json"
      )
    ) {
      const std::filesystem::path parent(
        (
          DetermineErrorDir()
          / std::filesystem::relative(path, DetermineJsonDir())
        ).parent_path()
      );

      const std::filesystem::path error_path(
        parent
        / (path.filename().string() + ".error")
      );

      AssertDeserializationFailure<
        our::types::ISomething
      >(
        path,
        our::jsonization::SomethingFrom,
        error_path
      );
    }
  }
}

TEST_CASE(
  "Test the serialization failure on an integer outside the range representable in JSON "
  "at .some_int of WithNumber"
) {
  for (
    const int64_t value
    : {
      9007199254740992LL,
      -9007199254740992LL
    }
  ) {
    std::shared_ptr<our::types::IWithNumber> instance(
      MustDeserializeTheFirstExpected<our::types::IWithNumber>(
        "WithNumber",
        our::jsonization::WithNumberFrom
      )
    );

    instance->set_some_int(value);

    AssertSerializationFailsAt(
      *instance,
      ".some_int"
    );
  }
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
