package verification_test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	aasjsonization "github.com/aas-core-works/aas-core3.0-golang/jsonization"
	aastesting "github.com/aas-core-works/aas-core3.0-golang/aastesting"
	aastypes "github.com/aas-core-works/aas-core3.0-golang/types"
	aasverification "github.com/aas-core-works/aas-core3.0-golang/verification"
)

// Assert that there are no verification errors in the `instance` de-serialized
// from `source`.
func assertNoVerificationErrors(
	t *testing.T,
	instance aastypes.IClass,
	source string,
) (ok bool) {
	errors := make([]*aasverification.VerificationError, 0)
	aasverification.Verify(
		instance,
		func(err *aasverification.VerificationError) (abort bool) {
			errors = append(errors, err)
			return
		},
	)

	ok = true
	if len(errors) > 0 {
		ok = false

		var sb strings.Builder

		sb.WriteString(
			fmt.Sprintf(
				"Expected no errors when verifying the instance de-serialized from "+
					"%s, but got %d error(s)\n",
				source, len(errors),
			),
		)

		for i, err := range errors {
			sb.WriteString(
				fmt.Sprintf(
					"Error %d:\n%s: %s\n",
					i+1,
					err.PathString(),
					err.Message,
				),
			)
		}

		jsonable, seriaErr := aasjsonization.ToJsonable(instance)
		if seriaErr != nil {
			panic(
				fmt.Sprintf(
					"Failed to serialize instance to JSON obtained from %s: %s",
					source, seriaErr.Error(),
				),
			)
		}
		jsonableBytes, err := json.Marshal(jsonable)
		if err != nil {
			panic(
				fmt.Sprintf(
					"Failed to marshal to JSON an instance serialized from %s: %s",
					source, err.Error(),
				),
			)
		}

		sb.WriteString("Instance:\n")
		sb.WriteString(string(jsonableBytes))

		t.Fatal(sb.String())
	}
	return
}

// Assert that either the verification errors match the recorded ones at `pth`, if
// [aastesting.RecordMode] is set, or re-record the verification errors at `pth`.
func assertEqualsExpectedOrRerecordVerificationErrors(
	t *testing.T,
	errors []*aasverification.VerificationError,
	source string,
	expectedPth string,
) (ok bool) {
	ok = true
	if len(errors) == 0 {
		ok = false
		t.Fatalf(
			"Expected at least one verification error, "+
				"but got none when verifying the model loaded from: %s",
			source,
		)
	}

	parts := make([]string, len(errors))
	for i, verErr := range errors {
		parts[i] = fmt.Sprintf(
			"%s: %s",
			verErr.PathString(),
			verErr.Message,
		)
	}

	// Add a newline for POSIX systems
	got := strings.Replace(strings.Join(parts, ";\n"), "\r\n", "\n", -1) + "\n"

	if aastesting.RecordMode {
		parent := filepath.Dir(expectedPth)
		err := os.MkdirAll(parent, os.ModePerm)
		if err != nil {
			panic(
				fmt.Sprintf(
					"Failed to create the directory %s: %s", parent, err.Error(),
				),
			)
		}

		err = os.WriteFile(expectedPth, []byte(got), 0644)
		if err != nil {
			ok = false
			t.Fatalf("Failed to write to %s: %s", expectedPth, err.Error())
			return
		}
	} else {
		_, err := os.Stat(expectedPth)
		if err != nil {
			ok = false
			t.Fatalf(
				"Failed to stat the file %s: %s; if the file does not exist, "+
					"you probably want to record the test data by "+
					"setting the environment variable %s",
				expectedPth, err.Error(), aastesting.RecordModeEnvironmentVariableName,
			)
			return
		}

		var bb []byte
		bb, err = os.ReadFile(expectedPth)
		if err != nil {
			ok = false
			t.Fatalf("Failed to read from %s: %s", expectedPth, err.Error())
			return
		}
		expected := strings.ReplaceAll(string(bb), "\r\n", "\n")

		if expected != got {
			ok = false
			t.Fatalf(
				"The expected verification errors (read from %s) in the model "+
					"de-serialized from %s do not match the obtained ones. "+
					"Expected:\n%s\nGot:\n%s",
				expectedPth, source, expected, got,
			)
			return
		}
	}
	return
}

func TestExtensionOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Extension",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ExtensionFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestExtensionFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Extension",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ExtensionFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAdministrativeInformationOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"AdministrativeInformation",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.AdministrativeInformationFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAdministrativeInformationFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"AdministrativeInformation",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.AdministrativeInformationFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestQualifierOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Qualifier",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.QualifierFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestQualifierFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Qualifier",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.QualifierFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAssetAdministrationShellOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"AssetAdministrationShell",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.AssetAdministrationShellFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAssetAdministrationShellFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"AssetAdministrationShell",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.AssetAdministrationShellFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAssetInformationOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"AssetInformation",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.AssetInformationFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAssetInformationFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"AssetInformation",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.AssetInformationFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestResourceOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Resource",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ResourceFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestResourceFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Resource",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ResourceFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSpecificAssetIDOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"SpecificAssetId",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.SpecificAssetIDFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSpecificAssetIDFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"SpecificAssetId",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.SpecificAssetIDFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Submodel",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.SubmodelFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Submodel",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.SubmodelFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestRelationshipElementOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"RelationshipElement",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.RelationshipElementFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestRelationshipElementFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"RelationshipElement",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.RelationshipElementFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelElementListOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"SubmodelElementList",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.SubmodelElementListFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelElementListFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"SubmodelElementList",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.SubmodelElementListFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestSubmodelElementCollectionOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"SubmodelElementCollection",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.SubmodelElementCollectionFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestSubmodelElementCollectionFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"SubmodelElementCollection",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.SubmodelElementCollectionFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestPropertyOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Property",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.PropertyFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestPropertyFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Property",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.PropertyFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestMultiLanguagePropertyOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"MultiLanguageProperty",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.MultiLanguagePropertyFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestMultiLanguagePropertyFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"MultiLanguageProperty",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.MultiLanguagePropertyFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestRangeOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Range",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.RangeFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestRangeFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Range",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.RangeFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestReferenceElementOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"ReferenceElement",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ReferenceElementFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestReferenceElementFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"ReferenceElement",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ReferenceElementFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestBlobOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Blob",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.BlobFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestBlobFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Blob",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.BlobFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestFileOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"File",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.FileFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestFileFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"File",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.FileFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestAnnotatedRelationshipElementOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"AnnotatedRelationshipElement",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.AnnotatedRelationshipElementFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestAnnotatedRelationshipElementFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"AnnotatedRelationshipElement",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.AnnotatedRelationshipElementFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEntityOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Entity",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.EntityFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEntityFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Entity",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.EntityFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEventPayloadOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"EventPayload",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.EventPayloadFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEventPayloadFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"EventPayload",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.EventPayloadFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestBasicEventElementOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"BasicEventElement",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.BasicEventElementFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestBasicEventElementFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"BasicEventElement",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.BasicEventElementFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestOperationOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Operation",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.OperationFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestOperationFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Operation",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.OperationFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestOperationVariableOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"OperationVariable",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.OperationVariableFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestOperationVariableFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"OperationVariable",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.OperationVariableFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestCapabilityOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Capability",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.CapabilityFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestCapabilityFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Capability",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.CapabilityFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestConceptDescriptionOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"ConceptDescription",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ConceptDescriptionFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestConceptDescriptionFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"ConceptDescription",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ConceptDescriptionFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestReferenceOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Reference",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ReferenceFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestReferenceFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Reference",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ReferenceFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestKeyOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Key",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.KeyFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestKeyFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Key",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.KeyFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringNameTypeOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LangStringNameType",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LangStringNameTypeFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringNameTypeFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LangStringNameType",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LangStringNameTypeFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringTextTypeOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LangStringTextType",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LangStringTextTypeFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringTextTypeFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LangStringTextType",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LangStringTextTypeFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEnvironmentOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"Environment",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.EnvironmentFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEnvironmentFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"Environment",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.EnvironmentFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestEmbeddedDataSpecificationOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"EmbeddedDataSpecification",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.EmbeddedDataSpecificationFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestEmbeddedDataSpecificationFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"EmbeddedDataSpecification",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.EmbeddedDataSpecificationFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLevelTypeOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LevelType",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LevelTypeFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLevelTypeFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LevelType",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LevelTypeFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestValueReferencePairOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"ValueReferencePair",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ValueReferencePairFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestValueReferencePairFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"ValueReferencePair",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ValueReferencePairFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestValueListOK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"ValueList",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.ValueListFromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestValueListFail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"ValueList",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.ValueListFromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringPreferredNameTypeIEC61360OK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LangStringPreferredNameTypeIec61360",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LangStringPreferredNameTypeIEC61360FromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringPreferredNameTypeIEC61360Fail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LangStringPreferredNameTypeIec61360",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LangStringPreferredNameTypeIEC61360FromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringShortNameTypeIEC61360OK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LangStringShortNameTypeIec61360",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LangStringShortNameTypeIEC61360FromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringShortNameTypeIEC61360Fail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LangStringShortNameTypeIec61360",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LangStringShortNameTypeIEC61360FromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestLangStringDefinitionTypeIEC61360OK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"LangStringDefinitionTypeIec61360",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.LangStringDefinitionTypeIEC61360FromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestLangStringDefinitionTypeIEC61360Fail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"LangStringDefinitionTypeIec61360",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.LangStringDefinitionTypeIEC61360FromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

func TestDataSpecificationIEC61360OK(t *testing.T) {
	pths := aastesting.FindFilesBySuffixRecursively(
		filepath.Join(
			aastesting.TestDataDir,
			"Json",
			"Expected",
			"DataSpecificationIec61360",
		),
		".json",
	)
	sort.Strings(pths)

	for _, pth := range pths {
		jsonable := aastesting.MustReadJsonable(
			pth,
		)

		deserialized, deseriaErr := aasjsonization.DataSpecificationIEC61360FromJsonable(
			jsonable,
		)
		if deseriaErr != nil {
			t.Fatalf(
				"Unexpected deserialization error from %s: %s",
				pth, deseriaErr.Error(),
			)
			return
		}

		var errors []*aasverification.VerificationError
		aasverification.Verify(
			deserialized,
			func(veriErr *aasverification.VerificationError) (abort bool) {
				errors = append(errors, veriErr)
				return
			},
		)

		ok := assertNoVerificationErrors(
			t,
			deserialized,
			pth,
		)
		if !ok {
			return
		}
	}
}

func TestDataSpecificationIEC61360Fail(t *testing.T) {
	pattern := filepath.Join(
		aastesting.TestDataDir,
		"Json",
		"Unexpected",
		"Invalid",
		"*",  // This asterisk represents the cause.
		"DataSpecificationIec61360",
	)

	causeDirs, err := filepath.Glob(pattern)
	if err != nil {
		panic(
			fmt.Sprintf(
				"Failed to find cause directories matching %s: %s",
				pattern, err.Error(),
			),
		)
	}

	for _, causeDir := range causeDirs {
		pths := aastesting.FindFilesBySuffixRecursively(
			causeDir,
			".json",
		)
		sort.Strings(pths)

		for _, pth := range pths {
			jsonable := aastesting.MustReadJsonable(
				pth,
			)

			relPth, err := filepath.Rel(aastesting.TestDataDir, pth)
			if err != nil {
				panic(
					fmt.Sprintf(
						"Failed to compute the relative path of %s to %s: %s",
						aastesting.TestDataDir, pth, err.Error(),
					),
				)
			}

			expectedPth := filepath.Join(
				aastesting.TestDataDir,
				"VerificationError",
				filepath.Dir(relPth),
				filepath.Base(relPth)+".errors",
			)

			deserialized, deseriaErr := aasjsonization.DataSpecificationIEC61360FromJsonable(
				jsonable,
			)
			if deseriaErr != nil {
				t.Fatalf(
					"Unexpected deserialization error from %s: %s",
					pth, deseriaErr.Error(),
				)
				return
			}

			var errors []*aasverification.VerificationError
			aasverification.Verify(
				deserialized,
				func(err *aasverification.VerificationError) (abort bool) {
					errors = append(errors, err)
					return
				},
			)

			ok := assertEqualsExpectedOrRerecordVerificationErrors(
				t,
				errors,
				pth,
				expectedPth,
			)
			if !ok {
				return
			}
		}
	}
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
