package types_is_xxx_test

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"testing"
	ourtesting "github.com/dummy-works/dummy/ourtesting"
	ourtypes "github.com/dummy-works/dummy/types"
)

func TestIsXxxOnAnInstanceOfStructuralFirst(t *testing.T) {
	instance := ourtesting.MustLoadMinimalStructuralFirst()

	if !ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be true on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IStructuralFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfStructuralSecond(t *testing.T) {
	instance := ourtesting.MustLoadMinimalStructuralSecond()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be true on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IStructuralSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfMixedAbstractDescendantOne(t *testing.T) {
	instance := ourtesting.MustLoadMinimalMixedAbstractDescendantOne()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be true on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IMixedAbstractDescendantOne with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfMixedAbstractDescendantTwo(t *testing.T) {
	instance := ourtesting.MustLoadMinimalMixedAbstractDescendantTwo()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be true on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IMixedAbstractDescendantTwo with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfMixedConcreteWithDescendants(t *testing.T) {
	instance := ourtesting.MustLoadMinimalMixedConcreteWithDescendants()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be true on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IMixedConcreteWithDescendants with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfMixedConcreteWithDescendantsChild(t *testing.T) {
	instance := ourtesting.MustLoadMinimalMixedConcreteWithDescendantsChild()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be true on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be true on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IMixedConcreteWithDescendantsChild with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfMixedConcreteLeaf(t *testing.T) {
	instance := ourtesting.MustLoadMinimalMixedConcreteLeaf()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be true on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IMixedConcreteLeaf with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfModelTypedFirst(t *testing.T) {
	instance := ourtesting.MustLoadMinimalModelTypedFirst()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be true on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IModelTypedFirst with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfModelTypedSecond(t *testing.T) {
	instance := ourtesting.MustLoadMinimalModelTypedSecond()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be true on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be false on an instance " +
			"of IModelTypedSecond with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

func TestIsXxxOnAnInstanceOfSomething(t *testing.T) {
	instance := ourtesting.MustLoadMinimalSomething()

	if ourtypes.IsStructuralFirst(instance) {
		t.Errorf(
			"Expected IsStructuralFirst to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsStructuralSecond(instance) {
		t.Errorf(
			"Expected IsStructuralSecond to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantOne(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantOne to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedAbstractDescendantTwo(instance) {
		t.Errorf(
			"Expected IsMixedAbstractDescendantTwo to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendants(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendants to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteWithDescendantsChild(instance) {
		t.Errorf(
			"Expected IsMixedConcreteWithDescendantsChild to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsMixedConcreteLeaf(instance) {
		t.Errorf(
			"Expected IsMixedConcreteLeaf to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedFirst(instance) {
		t.Errorf(
			"Expected IsModelTypedFirst to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if ourtypes.IsModelTypedSecond(instance) {
		t.Errorf(
			"Expected IsModelTypedSecond to be false on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}

	if !ourtypes.IsSomething(instance) {
		t.Errorf(
			"Expected IsSomething to be true on an instance " +
			"of ISomething with runtime type %T and with model type %v",
			instance, instance.ModelType(),
		)
	}
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
