"""Test JSON de/serialization of concrete classes."""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


# pylint: disable=missing-docstring


import json
import math
from typing import Any
import unittest


import dummy.jsonization as our_jsonization


import tests.common
import tests.common_jsonization


class TestRoundTrips(unittest.TestCase):
    def test_leaf(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'Leaf'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.leaf_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_ordered_container(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'OrderedContainer'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.ordered_container_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_unordered_container(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'UnorderedContainer'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.unordered_container_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_global_attribute(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'GlobalAttribute'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.global_attribute_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_local_attribute(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'LocalAttribute'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.local_attribute_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_attribute_operand(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'AttributeOperand'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.attribute_operand_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_string_literal(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'StringLiteral'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.string_literal_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_number_literal(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'NumberLiteral'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.number_literal_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))

    def test_something(self) -> None:
        for path in sorted(
            (
                tests.common.TEST_DATA_DIR
                / "Json"
                / "Expected"
                / 'Something'
            ).glob("**/*.json")
        ):
            with path.open("rt") as fid:
                original_jsonable = json.load(fid)

            instance = our_jsonization.something_from_jsonable(
                original_jsonable
            )

            another_jsonable = our_jsonization.to_jsonable(instance)

            mismatches = tests.common_jsonization.check_equal(
                original_jsonable,
                another_jsonable
            )
            self.assertListEqual([], list(map(str, mismatches)))


def _load_the_first_expected(model_type: str) -> Any:
    """Load the first recorded example of the ``model_type``."""
    paths = sorted(
        (
            tests.common.TEST_DATA_DIR
            / "Json"
            / "Expected"
            / model_type
        ).glob("**/*.json")
    )

    assert len(paths) > 0, (
        f"Expected at least one recorded example of {model_type}, but got none"
    )

    with paths[0].open("rt") as fid:
        return json.load(fid)


class TestSerializationFailures(unittest.TestCase):
    def test_number_literal_number_non_finite(self) -> None:
        for value in [math.inf, -math.inf, math.nan]:
            instance = our_jsonization.number_literal_from_jsonable(
                _load_the_first_expected('NumberLiteral')
            )

            instance.number = value

            with self.assertRaises(
                our_jsonization.SerializationException
            ) as context_manager:
                our_jsonization.to_jsonable(instance)

            self.assertEqual(
                '.number',
                context_manager.exception.path
            )


if __name__ == "__main__":
    unittest.main()


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
