package ourtesting

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import (
	"fmt"
	ourtypes "github.com/dummy-works/dummy/types"
)

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualItem(
	that ourtypes.IItem,
	other ourtypes.IItem,
) bool {
	thatName := that.Name()
	otherName := other.Name()
	if thatName != otherName {
		return false
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualSomething(
	that ourtypes.ISomething,
	other ourtypes.ISomething,
) bool {
	thatTexts := that.Texts()
	otherTexts := other.Texts()
	if !deepEqualListOf_string(
		thatTexts,
		otherTexts,
	) {
		return false
	}

	thatNumbers := that.Numbers()
	otherNumbers := other.Numbers()
	if !deepEqualListOf_long(
		thatNumbers,
		otherNumbers,
	) {
		return false
	}

	thatKinds := that.Kinds()
	otherKinds := other.Kinds()
	if !deepEqualListOf_Kind(
		thatKinds,
		otherKinds,
	) {
		return false
	}

	thatCodes := that.Codes()
	otherCodes := other.Codes()
	if !deepEqualListOf_string(
		thatCodes,
		otherCodes,
	) {
		return false
	}

	thatItems := that.Items()
	otherItems := other.Items()
	if !deepEqualListOf_IItem(
		thatItems,
		otherItems,
	) {
		return false
	}

	thatOptionalTexts := that.OptionalTexts()
	otherOptionalTexts := other.OptionalTexts()
	if
		(thatOptionalTexts == nil && otherOptionalTexts != nil) ||
		(thatOptionalTexts != nil && otherOptionalTexts == nil) {
		return false
	}
	if thatOptionalTexts != nil {
		if !deepEqualListOf_string(
			thatOptionalTexts,
			otherOptionalTexts,
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` instance.
//
// The deep equality means that all the properties are checked for equality recursively.
func deepEqualRegistry(
	that ourtypes.IRegistry,
	other ourtypes.IRegistry,
) bool {
	thatCounts := that.Counts()
	otherCounts := other.Counts()
	if !deepEqualDictOf_string_long(
		thatCounts,
		otherCounts,
	) {
		return false
	}

	thatCountsByNumber := that.CountsByNumber()
	otherCountsByNumber := other.CountsByNumber()
	if !deepEqualDictOf_long_long(
		thatCountsByNumber,
		otherCountsByNumber,
	) {
		return false
	}

	thatWeights := that.Weights()
	otherWeights := other.Weights()
	if !deepEqualDictOf_Direction_long(
		thatWeights,
		otherWeights,
	) {
		return false
	}

	thatKindsByCode := that.KindsByCode()
	otherKindsByCode := other.KindsByCode()
	if !deepEqualDictOf_string_Kind(
		thatKindsByCode,
		otherKindsByCode,
	) {
		return false
	}

	thatCodesByName := that.CodesByName()
	otherCodesByName := other.CodesByName()
	if !deepEqualDictOf_string_string(
		thatCodesByName,
		otherCodesByName,
	) {
		return false
	}

	thatItemsByName := that.ItemsByName()
	otherItemsByName := other.ItemsByName()
	if !deepEqualDictOf_string_IItem(
		thatItemsByName,
		otherItemsByName,
	) {
		return false
	}

	thatLabels := that.Labels()
	otherLabels := other.Labels()
	if !deepEqualDictOf_string_ListOf_ListOf_DictOf_long_string(
		thatLabels,
		otherLabels,
	) {
		return false
	}

	thatOptionalCounts := that.OptionalCounts()
	otherOptionalCounts := other.OptionalCounts()
	if
		(thatOptionalCounts == nil && otherOptionalCounts != nil) ||
		(thatOptionalCounts != nil && otherOptionalCounts == nil) {
		return false
	}
	if thatOptionalCounts != nil {
		if !deepEqualDictOf_string_long(
			thatOptionalCounts,
			otherOptionalCounts,
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_string(
	that []string,
	other []string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if that[i] != other[i] {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_long(
	that []int64,
	other []int64,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if that[i] != other[i] {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_Kind(
	that []ourtypes.Kind,
	other []ourtypes.Kind,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if that[i] != other[i] {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_IItem(
	that []ourtypes.IItem,
	other []ourtypes.IItem,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if !DeepEqual(
			that[i],
			other[i],
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_string_long(
	that map[string]int64,
	other map[string]int64,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_long_long(
	that map[int64]int64,
	other map[int64]int64,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_Direction_long(
	that map[ourtypes.Direction]int64,
	other map[ourtypes.Direction]int64,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_string_Kind(
	that map[string]ourtypes.Kind,
	other map[string]ourtypes.Kind,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_string_string(
	that map[string]string,
	other map[string]string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_string_IItem(
	that map[string]ourtypes.IItem,
	other map[string]ourtypes.IItem,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if !DeepEqual(
			thatValue,
			otherValue,
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_string_ListOf_ListOf_DictOf_long_string(
	that map[string][][]map[int64]string,
	other map[string][][]map[int64]string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if !deepEqualListOf_ListOf_DictOf_long_string(
			thatValue,
			otherValue,
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_ListOf_DictOf_long_string(
	that [][]map[int64]string,
	other [][]map[int64]string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if !deepEqualListOf_DictOf_long_string(
			that[i],
			other[i],
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualListOf_DictOf_long_string(
	that []map[int64]string,
	other []map[int64]string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for i := range that {
		if !deepEqualDictOf_long_string(
			that[i],
			other[i],
		) {
			return false
		}
	}

	return true
}

// Perform a comparison for deep equality between `that` and `other` container,
// recursing into its items.
func deepEqualDictOf_long_string(
	that map[int64]string,
	other map[int64]string,
) bool {
	if len(that) != len(other) {
		return false
	}

	for k, thatValue := range that {
		otherValue, ok := other[k]
		if !ok {
			return false
		}

		if thatValue != otherValue {
			return false
		}
	}

	return true
}

func DeepEqual(
	that ourtypes.IClass,
	other ourtypes.IClass,
) bool {
	if that.ModelType() != other.ModelType() {
		return false
	}

	switch that.ModelType() {
	case ourtypes.ModelTypeItem:
		return deepEqualItem(
			that.(ourtypes.IItem),
			other.(ourtypes.IItem),
		)
	case ourtypes.ModelTypeSomething:
		return deepEqualSomething(
			that.(ourtypes.ISomething),
			other.(ourtypes.ISomething),
		)
	case ourtypes.ModelTypeRegistry:
		return deepEqualRegistry(
			that.(ourtypes.IRegistry),
			other.(ourtypes.IRegistry),
		)
	}

	panic(fmt.Sprintf("Unexpected model type: %d", that.ModelType()))
}

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
