/**
 * Execute all common XMLization loader helpers once.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as TestCommonXmlization from "./commonXmlization";

test("commonXmlization loaders for Something", () => {
  expect(TestCommonXmlization.loadMinimalSomething()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalSomething()).not.toBeNull();
});

test("commonXmlization loaders for Collection", () => {
  expect(TestCommonXmlization.loadMinimalCollection()).not.toBeNull();
  expect(TestCommonXmlization.loadMaximalCollection()).not.toBeNull();
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
