/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */

using Aas = dummy;  // renamed

using System.Linq;  // can't alias
using NUnit.Framework;  // can't alias

namespace dummy.Tests
{
    public class TestVerificationOfEnums
    {
        [Test]
        public void Test_Kind_valid()
        {
            var errors = Aas.Verification.VerifyKind(
                Aas.Kind.Alpha).ToList();

            Assert.IsEmpty(errors);
        }  // void Test_Kind_valid

        [Test]
        public void Test_Kind_invalid()
        {
            int valueAsInt = -1;
            Aas.Kind value = (Aas.Kind)valueAsInt;

            var errors = Aas.Verification.VerifyKind(
                value).ToList();

            Assert.AreEqual(1, errors.Count);
            Assert.AreEqual("Invalid Kind: -1", errors[0].Cause);
        }  // void Test_Kind_invalid
    }  // class TestVerificationOfEnums
}  // namespace dummy.Tests

/*
 * This code has been automatically generated by aas-core-codegen.
 * Do NOT edit or append.
 */
