"""
Verify that the instances of the meta-model satisfy the invariants.

Here is an example how to verify an instance of :py:class:`dummy.types.Item`:

.. code-block::

    import dummy.types as our_types
    import dummy.verification as our_verification

    an_instance = our_types.Item(
        # ... some constructor arguments ...
    )

    for error in our_verification.verify(an_instance):
        print(f"{error.cause} at: {error.path}")
"""


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.


import collections.abc
import math
import re
import struct
import sys
from typing import (
    Any,
    Callable,
    Iterable,
    Iterator,
    List,
    Mapping,
    Optional,
    Pattern,
    Sequence,
    Set,
    Tuple,
    Union
)

if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final

from dummy import (
    constants as our_constants,
    reporting as our_reporting,
    types as our_types,
)


PropertySegment = our_reporting.PropertySegment
IndexSegment = our_reporting.IndexSegment
KeySegment = our_reporting.KeySegment
Segment = our_reporting.Segment
Path = our_reporting.Path

Error = our_reporting.Error


def if_with_a_single_branch(
    text: str
) -> bool:
    """Check the if-statement with a single branch and no default."""
    # pylint: disable=all
    if len(text) > 10:
        return False
    return True


def if_elif_else(
    number: int,
    text: str
) -> bool:
    """
    Check the chain of ``if``, ``elif`` and ``else`` where all the branches return.

    The last ``elif`` compares against a constant, but it is still a branch of
    the if-statement as the chain does not start as a switch.
    """
    # pylint: disable=all
    if (
        (
            number < 0
            and len(text) > 0
        )
    ):
        return False
    elif (
        (
            number > 100
            or text == 'unlucky'
        )
    ):
        return False
    elif number == 13:
        return False
    else:
        doubled = (
            ((((number + number) + number) + number) - number) - number)
        return doubled < 150


def if_with_pass(
    flag: bool,
    number: int
) -> bool:
    """Check the if-statement with an empty branch."""
    # pylint: disable=all
    if (
        (
            flag
            and number > 5
        )
    ):
        pass
    elif not flag:
        return number < 50
    return True


def if_in_default_of_switch(
    kind: our_types.Kind,
    number: int
) -> bool:
    """
    Check the ``elif`` which does not compare the subject of the switch.

    The ``elif`` becomes an if-statement in the default of the switch, and nests
    a switch in turn.
    """
    # pylint: disable=all
    if kind == our_types.Kind.ALPHA:
        return number < 10
    else:
        if number < -5:
            if kind == our_types.Kind.BETA:
                return False
    return True


def if_with_non_null_in_condition(
    item: our_types.Item
) -> bool:
    """Check the condition which guards an optional value itself."""
    # pylint: disable=all
    if (
        (
            (item.optional_text is not None)
            and len(item.optional_text) > 5
        )
    ):
        return False
    return True


def if_with_reassigned_variable(
    number: int
) -> bool:
    """
    Check the variable defined before the if-statement and assigned in it.
    """
    # pylint: disable=all
    result = 0
    if (
        (
            number > 20
            and number < 30
        )
    ):
        result = number
    elif number < -20:
        result = -number
    return result < 25


def if_with_continue_in_for(
    number: int
) -> bool:
    """
    Check the ``continue`` in a branch of an if-statement nested in a for-loop.
    """
    # pylint: disable=all
    count = 0
    for i in range(0, 10):
        if (
            (
                (i % 2) == (0)
                or i > number
            )
        ):
            continue
        count = count + 1
    return count != 3


def narrowing_in_body(
    parent: Optional[our_types.Parent]
) -> bool:
    """Check the narrowing in the body of a branch by its condition."""
    # pylint: disable=all
    if (
        (
            (parent is not None)
            and isinstance(parent, our_types.ChildA)
        )
    ):
        return parent.a_only < 100
    return True


def narrowing_in_elif_and_else(
    parent: Optional[our_types.Parent]
) -> bool:
    """Check the narrowing by the negation of the previous conditions."""
    # pylint: disable=all
    if parent is None:
        return True
    elif not isinstance(parent, our_types.ChildB):
        return (
            (
                (parent.optional_text is None)
                or parent.optional_text != 'forbidden'
            ))
    else:
        return parent.b_only > 0


def narrowing_after_early_return(
    parent: Optional[our_types.Parent]
) -> bool:
    """
    Check the narrowing after an if-statement whose branch always returns.
    """
    # pylint: disable=all
    if (
        (
            (parent is None)
            or (not isinstance(parent, our_types.ChildB))
        )
    ):
        return True
    return parent.b_only < 50


def narrowing_after_the_only_completing_branch(
    parent: Optional[our_types.Parent]
) -> bool:
    """
    Check the narrowing after an if-statement whose ``else`` always returns.
    """
    # pylint: disable=all
    if (
        (
            (parent is not None)
            and isinstance(parent, our_types.ChildA)
        )
    ):
        pass
    else:
        return True
    return parent.a_only > -10


def child_as_have_texts(
    parents: List[our_types.Parent]
) -> bool:
    """
    Check the narrowing after the ``continue`` and the early return in a loop.
    """
    # pylint: disable=all
    for parent in parents:
        if not isinstance(parent, our_types.ChildA):
            continue
        if parent.optional_text is None:
            return False
        if len(parent.optional_text) < 1:
            return False
    return True


def texts_before_container_are_short(
    parents: List[our_types.Parent]
) -> bool:
    """
    Check the narrowing after the ``continue`` in a loop with a ``break``.
    """
    # pylint: disable=all
    total = 0
    for parent in parents:
        if isinstance(parent, our_types.Container):
            break
        if parent.optional_text is None:
            continue
        total = total + len(parent.optional_text)
    return total < 20


def text_or_default_is_short(
    parent: our_types.Parent
) -> bool:
    """Check the narrowing by the value assigned in a branch."""
    # pylint: disable=all
    text = parent.optional_text
    if text is None:
        text = 'default'
    return len(text) < 10


def last_child_a_is_small(
    parent: our_types.Parent,
    parents: List[our_types.Parent]
) -> bool:
    """
    Check the narrowing of a variable to a class by the assigned value.
    """
    # pylint: disable=all
    last = parent
    for other in parents:
        if isinstance(other, our_types.ChildA):
            last = other
            if last.a_only >= 1000:
                return False
    return True


def has_marker_in_tree(
    parent: our_types.Parent
) -> bool:
    """
    Check the recursive chain of ``isinstance`` checks with early returns.
    """
    # pylint: disable=all
    if (
        (
            (parent.optional_text is not None)
            and parent.optional_text == 'marker'
        )
    ):
        return True
    if isinstance(parent, our_types.Container):
        return (
            (
                (parent.children is not None)
                and (
                    any(
                        has_marker_in_tree(child)
                        for child in parent.children
                    )
                )
            ))
    return False


class _Transformer(
        our_types.AbstractTransformer[
            Iterator[Error]
        ]
):
    # noinspection PyMethodMayBeStatic
    def transform_item(
            self,
            that: our_types.Item
    ) -> Iterator[Error]:
        # No verification has been defined for Item.
        return
        # For this uncommon return-yield construction, see:
        # https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
        # noinspection PyUnreachableCode
        yield

    # noinspection PyMethodMayBeStatic
    def transform_child_a(
            self,
            that: our_types.ChildA
    ) -> Iterator[Error]:
        # No verification has been defined for ChildA.
        return
        # For this uncommon return-yield construction, see:
        # https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
        # noinspection PyUnreachableCode
        yield

    # noinspection PyMethodMayBeStatic
    def transform_child_b(
            self,
            that: our_types.ChildB
    ) -> Iterator[Error]:
        # No verification has been defined for ChildB.
        return
        # For this uncommon return-yield construction, see:
        # https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
        # noinspection PyUnreachableCode
        yield

    # noinspection PyMethodMayBeStatic
    def transform_container(
            self,
            that: our_types.Container
    ) -> Iterator[Error]:
        if that.children is not None:
            for i, an_item in enumerate(that.children):
                for error in self.transform(an_item):
                    error.path._prepend(
                        IndexSegment(
                            that.children,
                            i
                        )
                    )
                    error.path._prepend(
                        PropertySegment(
                            that,
                            'children'
                        )
                    )
                    yield error

    # noinspection PyMethodMayBeStatic
    def transform_something(
            self,
            that: our_types.Something
    ) -> Iterator[Error]:
        if not if_with_continue_in_for(that.number):
            yield Error(
                'Number must not be five or six'
            )

        if not if_with_reassigned_variable(that.number):
            yield Error(
                'Number must be neither between 25 and 29 nor below -24'
            )

        if not if_with_non_null_in_condition(that.item):
            yield Error(
                'Optional text of the item must be at most 5 characters long'
            )

        if not if_in_default_of_switch(that.kind, that.number):
            yield Error(
                'Number must be consistent with the kind'
            )

        if not if_with_pass(that.flag, that.number):
            yield Error(
                'Number must be small without the flag'
            )

        if not if_elif_else(that.number, that.text):
            yield Error(
                'Number and text must be acceptable'
            )

        if not if_with_a_single_branch(that.text):
            yield Error(
                'Text must be at most 10 characters long'
            )

        if not (
            not (that.optional_parent is not None)
            or (not has_marker_in_tree(that.optional_parent))
        ):
            yield Error(
                'Optional parent must have no marker in its tree'
            )

        if not (
            not (
                (
                    (that.optional_parent is not None)
                    and (that.parents is not None)
                )
            )
            or last_child_a_is_small(
                that.optional_parent,
                that.parents
            )
        ):
            yield Error(
                'Parents as Child_a must have a_only below one thousand'
            )

        if not (
            not (that.optional_parent is not None)
            or text_or_default_is_short(that.optional_parent)
        ):
            yield Error(
                'Text of the optional parent must be short'
            )

        if not (
            not (that.parents is not None)
            or texts_before_container_are_short(that.parents)
        ):
            yield Error(
                'Texts of parents before the first container must be short'
            )

        if not (
            not (that.parents is not None)
            or child_as_have_texts(that.parents)
        ):
            yield Error(
                'Parents as Child_a must have non-empty texts'
            )

        if not (
            narrowing_after_the_only_completing_branch(
                that.optional_parent
            )
        ):
            yield Error(
                'Optional parent as Child_a must have a_only above minus ten'
            )

        if not narrowing_after_early_return(that.optional_parent):
            yield Error(
                'Optional parent as Child_b must have a small b_only'
            )

        if not narrowing_in_elif_and_else(that.optional_parent):
            yield Error(
                'Optional parent must have an allowed text or a positive ' +
                'b_only'
            )

        if not narrowing_in_body(that.optional_parent):
            yield Error(
                'Optional parent as Child_a must have a small a_only'
            )

        for error in self.transform(that.item):
            error.path._prepend(
                PropertySegment(
                    that,
                    'item'
                )
            )
            yield error

        if that.optional_parent is not None:
            for error in self.transform(that.optional_parent):
                error.path._prepend(
                    PropertySegment(
                        that,
                        'optional_parent'
                    )
                )
                yield error

        if that.parents is not None:
            for i, an_item in enumerate(that.parents):
                for error in self.transform(an_item):
                    error.path._prepend(
                        IndexSegment(
                            that.parents,
                            i
                        )
                    )
                    error.path._prepend(
                        PropertySegment(
                            that,
                            'parents'
                        )
                    )
                    yield error


_TRANSFORMER = _Transformer()


def verify(
        that: our_types.Class
) -> Iterator[Error]:
    """
    Verify the constraints of :paramref:`that` recursively.

    :param that: instance whose constraints we want to verify
    :yield: constraint violations
    """
    yield from _TRANSFORMER.transform(that)


# This code has been automatically generated by aas-core-codegen.
# Do NOT edit or append.
