/**
 * Test `over{Enum}` functions.
 */

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.

import * as AasTypes from "../src/types";

test("over RecorD", () => {
  const expected: Array<AasTypes.RecorD> = [
    AasTypes.RecorD.Ok,
    AasTypes.RecorD.NotOk
  ];

  const got = new Array<AasTypes.RecorD>();
  for (const literal of AasTypes.overRecord()) {
    got.push(literal);
  }

  expect(got).toStrictEqual(expected);
});

// This code has been automatically generated by aas-core-codegen.
// Do NOT edit or append.
